src/App.js
src/components/molecules/NavBar/NavBar.js
src/components/molecules/UserList/UserList.scss
src/components/organisms/Chatbox/Chatbox.jsx
src/components/organisms/Chatbox/Chatbox.scss
src/components/organisms/EditProfileModal/EditProfileModal.tsx
src/components/organisms/EditProfileModal/index.ts
src/components/organisms/WithLoadedUsers/WithLoadedUsers.jsx
src/components/organisms/WithLoadedUsers/index.js
src/index.js
src/pages/Account/Account.scss
src/pages/Account/Profile.tsx
src/pages/Account/Questions.tsx
src/pages/Account/constants.ts
src/pages/EditProfilePage/EditProfilePage.scss
src/pages/EditProfilePage/EditProfilePage.tsx
src/pages/EditProfilePage/index.ts
src/scss/global.scss
src/types/Question.ts

:sparkles: add EditProfilePage

---

src/pages/JazzBar/Jazz/Jazz.scss
src/pages/JazzBar/Jazz/Jazz.tsx
src/scss/global.scss

:sparkles: add toggling full-screen checkbox

---

firestore.rules
functions/.gitignore
functions/index.js
functions/payment.js

Use (priviledged) service account to write to the table
Allow User to only read their own

Secure purchases table

---

src/components/molecules/JazzbarTableComponent/JazzbarTableComponent.tsx
src/components/molecules/TableComponent/TableComponent.tsx
src/components/molecules/UserProfilePicture/UserProfilePicture.tsx
src/components/organisms/Chatbox/Chatbox.tsx
src/components/organisms/Room/Room.tsx
src/components/venues/Jazzbar/components/MessageList.tsx
src/hooks/useSelector.ts
src/pages/ReactionPage/ReactionPage.tsx
src/types/Firestore.ts
src/types/Tidy.ts
src/utils/id.ts

We have a typing error where the User type has a id field despite this not always being the case. This is a WIP to fix it.

useKeyedSelector for adding object keys to values

---

functions/package.json

10 is currently the last stable version for firebase functions

Update functions node engine

---

src/pages/Account/Admin.tsx
src/scss/global.scss
src/types/Firestore.ts

Show venue list on admin page

---

src/pages/Account/Venue/VenueMapEdition/Container.tsx
src/pages/Admin/Venue/DetailsForm.tsx

Display other venues on the playa edit view

---

src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx
src/components/organisms/ProfileModal/UserInformationContent/UserInformationContent.tsx
src/pages/VenuePage/VenuePage.tsx

Add a create button, fix logout issues

Create in the SparkleVerse!

---

functions/venue.js

the function upsertRoom was being evaluated as deleteRoom

room form works when creating and/or updating a room

---

src/components/organisms/Chatbox/Chatbox.tsx
src/components/templates/Camp/Camp.tsx

useEffect was in an infinite loop because of users changing all the time

Prevent chat from crashing the page

---

functions/venue.js
src/api/admin.ts
src/pages/Account/Venue/VenueMapEdition/CampContainer.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx

- allow to change the room title
- remove current room from the other rooms on the camp preview
- change image input label

Room edition tweaks

---

src/components/templates/Camp/components/Map.tsx

Fixes: https://trello.com/c/FNnW0Sdu - When you enter a room within a camp, it does not correctly remember what room you are in.

Fix for When you enter a room within a camp, it does not correctly remember what room you are in.

---

src/components/molecules/OnlineStats/OnlineStats.tsx

Adds the number of current ongoing live events as well as the total number of venues and live participants.
The visual update is going to be in the upcoming PR.

add number of live events to search bar

---

src/components/organisms/DustStorm/DustStorm.tsx
src/components/templates/Playa/Playa.tsx

https://trello.com/c/ci7TFyGa
1. Get Dust storms Activation button back
2. Change the text of Dust storm alert

Get Dust storms Activation button back and fix copy of Dust storm alert

---

src/components/organisms/ChatDrawer/ChatDrawer.tsx
src/components/organisms/Room/LocalParticipant.tsx
src/components/organisms/Room/Participant.tsx
src/components/organisms/Room/Room.tsx
src/components/templates/ArtPiece/ArtPiece.tsx

https://trello.com/c/6AzgTJnw
1. Open chat by default on entering an art piece
2. Mute user twilio videos by default on entering on an Art Piece Venue
3. Get the profile modal on click on someone's avatar from the art piece video

Default Chat state, muted user videos and profile modals on an Art Piece Venue

---

src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
src/components/templates/Playa/Playa.scss
src/components/templates/Playa/Playa.tsx
src/scss/constants.scss
src/settings.ts

Live venues either have more than one person or a current event

Highlight live venues

---

src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/NavBar/playa.scss
src/components/molecules/OnlineStats/OnlineStats.tsx

Small topbar styling fixes - https://trello.com/c/5GumA16X

Small topbar styling fixes

---

functions/venue.js
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/components/templates/Playa/PlayaAdmin.tsx
src/components/templates/Playa/Router.tsx

Playa banner editor

---

package-lock.json
package.json
src/components/templates/Playa/Playa.tsx
src/components/templates/Playa/PlayaBackground.scss
src/components/templates/Playa/PlayaBackground.tsx
src/settings.ts

Add Playa background hue for Morning / Day / Evening / Night date parts  - https://trello.com/c/UGpUtd0M

Add Playa background hue for Morning / Day / Evening / Night date parts

---

package-lock.json
package.json
src/components/templates/Playa/Avatar.tsx
src/components/templates/Playa/AvatarLayer.scss
src/components/templates/Playa/AvatarLayer.tsx
src/components/templates/Playa/MyAvatar.tsx
src/components/templates/Playa/Playa.scss
src/components/templates/Playa/Playa.tsx
src/scss/constants.scss

- add avatars in a hexagon when in a video call
- add blinking green indicator
- show purple when someone is in a video
- update some of the texts

add avatars when in video group call

---

src/components/templates/Playa/Playa.scss
src/scss/constants.scss
src/settings.ts

Just the avatar shrinking portion of https://github.com/sparkletown/sparkle/pull/469

Shrink avatars

---

src/pages/VenuePage/VenuePage.tsx

Fixes the many re-renderings of the VenuePage component and it's children.

add single query for current venue in venue page

---

src/components/templates/Camp/Camp.tsx
src/components/templates/Camp/Router.tsx
src/components/templates/Camp/components/RoomCard.tsx
src/components/templates/Camp/components/RoomList.tsx
src/components/templates/Camp/components/RoomModal.tsx
src/components/templates/Playa/PlayaAdmin.tsx
src/components/templates/Playa/Router.tsx

Do not use hooks which depend on AppRouter context in the context of a subrouter

Fix camp venue loading

---

functions/venue.js
src/pages/Admin/Venue/Rooms/RoomDeleteModal.scss
src/pages/Admin/Venue/Rooms/RoomDeleteModal.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx

Add an ability to delete rooms - https://trello.com/c/PM6cxLri

Add an ability to delete rooms

---

src/components/templates/Playa/Playa.scss

Make shout outs go highest on Z axis so they don't get obscured - https://trello.com/c/XAYil46W

Make shout outs go highest on Z axis so they don't get obscured

---

src/components/templates/Playa/MyAvatar.tsx
src/components/templates/Playa/Playa.scss

Formatting micro issue on personal name tag on Playa - https://trello.com/c/Wp87ivgW

Formatting micro issue on personal name tag on Playa

---

src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/NavBar/playa.scss
src/components/molecules/PlayaTime/PlayaTime.scss
src/components/molecules/PlayaTime/PlayaTime.tsx
src/components/molecules/PlayaTime/index.js

Add current Playa time next to SparkleVerse logo - https://trello.com/c/iqcNaKGW

Add current Playa time next to SparkleVerse logo

---

src/components/templates/Audience/Audience.scss
src/components/templates/Audience/Audience.tsx

- add layout for seats
- position chat in top right corner (not sure if flex broke it or if it wasn't positioned at all)
- add keys for the components so react can stop crying

add layout for seats and position tweaks

---

src/components/templates/Playa/Avatar.tsx
src/components/templates/Playa/AvatarPartygoers.tsx
src/components/templates/Playa/MyAvatar.tsx
src/components/templates/Playa/Playa.scss
src/scss/constants.scss

https://trello.com/c/1nEd2lc8/266-bugs-on-video-ui
Make the pop up white text on transparant grey background so that it works in dark and light mode
When I start a video chat, I get a white flashing aura that I can see and that other people can see. There is also a "Dino's live video chat" bubble- like the name, but 3x bigger positioned above (see pic below)
No matter who is on the chat, everyone (Dino and all his guests) should see Dino's white aura, and their mini-avatar in the aura. (everyone should see the same). Including the "Dino's live video chat" bubble.

Video UI avatar additions

---

src/components/templates/Playa/AvatarImage.tsx
src/components/templates/Playa/Playa.scss

Optimize avatar image useEffect dependencies, fix invisible video active status css.

Optimize avatar image useEffect dependencies, fix invisible video active status css.

---

src/pages/Account/Account.scss
src/pages/Account/Step4.tsx
src/pages/Account/Step5.tsx

Still waiting for some additional text for the "consent" and "temple etiquette" videos, but they are no longer placeholders. I think they will be providing at least one more video, so will update again shortly.

updated thumbnails

---

functions/venue.js
src/api/admin.ts
src/components/templates/Playa/Playa.tsx
src/hooks/useRoles.ts
src/pages/Account/Venue/VenueMapEdition/PlayaContainer.tsx
src/pages/Admin/Admin.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/VenueOwnersModal.tsx

- Prevent venue hover for hidden venues
- allowAll flag for giving everyone admin tools access
- Do not load hidden venues into playa container
- Hide placement preview and self placement tools when not in burn mode
- Ability to remove an owner

SparkleVerse fixes

---

src/components/context/ChatContext.tsx
src/components/organisms/ChatDrawer/ChatDrawer.tsx
src/settings.ts

Is there a way to filter at the firebase back end rather than the front end?

hide messages from before seed

---

src/pages/Admin/AdminEditComponent.tsx

this seems to save the placement co-ordinates correctly

do not unset background image width

---

src/components/templates/Playa/Playa.tsx

Remove add edit button from the side menu

remove add/edit button

---

src/components/templates/Camp/Camp.tsx

useEffect and useState was looping and causing the counters to flicker infinitely

remove state to avoid counter flickering

---

src/components/molecules/TableHeader/TableHeader.tsx
src/components/organisms/Room/Room.scss
src/components/templates/Jazzbar/JazzTab/JazzTab.scss
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx

- Fixes the table counter where is says "-1"
- Video should be at the top now, instead of centered
- Mute button for reactions

jazzbar css tweaks and mute button

---

src/components/templates/Playa/Playa.scss
src/components/templates/Playa/Playa.tsx
src/scss/constants.scss
src/settings.ts

- Enlarge my avatar
- Fix counter display

fix counter display and positioning

---

src/components/molecules/TableComponent/TableComponent.tsx
src/components/molecules/TableHeader/TableHeader.tsx
src/components/templates/ConversationSpace/ConversationSpace.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/pages/FriendShipPage/FriendShipPage.tsx

The logic was using the references to display the users inside but the join function was passing title to the firebase

fix jazzbar tables not showing participants

---

src/components/templates/AvatarGrid/RoomModal.tsx
src/components/templates/Camp/components/Map.tsx
src/components/templates/Camp/components/RoomList.tsx
src/components/templates/Camp/components/RoomModal.tsx
src/components/templates/ConversationSpace/ConversationSpace.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/components/templates/PartyMap/PartyMapPage.tsx
src/components/templates/PartyMap/RoomModal/RoomModal.tsx
src/utils/useLocationUpdateEffect.ts

- Add the correct counting logic in the rest of the templates
- Add /room suffix to keep only 1 room at a time
P.S. @thecadams  Please take a look at the .log file that I've committed. I can't remove it and it's being generated all the time, would you mind if I add it to git.ignore?

fix counting logic in the other venues

---

functions/venue.js

Audience added to list of valid templates for venue creation

Fix: Audience added to list of valid templates for venue creation

---

.vscode/settings.json
functions/venue.js
src/api/admin.ts
src/components/molecules/UserProfilePicture/UserProfilePicture.scss
src/components/molecules/UserProfilePicture/UserProfilePicture.tsx
src/components/templates/AvatarGrid/AvatarGrid.scss
src/components/templates/Camp/Camp.tsx
src/components/templates/Camp/components/Map.scss
src/components/templates/Camp/components/Map.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/Venue.ts

Add grid to the clickable map a.k.a themecamp

add avatar grid to camp template

---

src/components/molecules/UserProfilePicture/UserProfilePicture.tsx
src/components/templates/Camp/Camp.scss
src/components/templates/Camp/components/Map.scss
src/components/templates/Camp/components/Map.tsx
src/types/CampVenue.ts

- Fix mini avatars showing by default
- Add glow and remove adjacent bubbles
- Hold key movement
- Jumping animation for your own avatar
- Disable arrow key scrolling

add additional tweaks to camp grid

---

src/components/templates/Camp/components/Map.scss
src/components/templates/Camp/components/Map.tsx

- fixes the streching of the background when grid is disabled
- removes the white background glow of the rooms (currently for all of the camp venues)

fix camp grid and remove room glow

---

functions/venue.js

* When user is added to the list of venue owners, the user is automatically added to the list of admins
* When removing a user from the list of owners, if the user does not own any other venue (not in owners list), user is automatically removed from the list of admins

New owner added to admins list

---

.gitignore
src/components/molecules/NavBar/NavBar.tsx
src/components/organisms/RadioModal/RadioModal.tsx
src/hooks/roles.ts
src/hooks/useDebugWarnLog.ts
src/pages/Admin/Admin.tsx
src/pages/Admin/VenueOwnersModal.tsx
src/types/Firestore.ts
src/types/SparkleSelector.ts
src/utils/filter.ts
src/utils/selectors.ts

(ref: https://trello.com/c/aKYvJutd)
The `/admin/venue/:venueId` page would take a long time to load, sometimes hanging the UI for quite a while before letting users interact with it. This was even evident when a user only had access to as little as 2 venues.
This PR should improve the performance by reducing the number of unnecessary re-renders (and simplify/clean up some code patterns along the way).
I think there are likely still some other areas this could be improved still, but a partial fix shipped sooner is better than no fix shipped.

Improve Admin component's venues loading performance

---

functions/venue.js
src/api/admin.ts
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/VenueWizard.tsx

* If parentId is passed as part of URL query , it is included as the default venue parent in the details form
* When a venue is created/edited so that it has a _venue parent_ that venues owner(s) is added to the owners array of the current venue

Venue parent added to owner list

---

src/components/templates/FireBarrel/FireBarrel.tsx
src/components/templates/FireBarrel/FireSeat.tsx
src/components/templates/FireBarrel/useVideo.tsx

**Sub-PR:** to https://github.com/sparkletown/sparkle/pull/736 (should be merged back to that, not `staging`)

[Sub-PR] Firebarrel Template: useVideo() hook

---

src/components/templates/Camp/Camp.tsx
src/components/templates/Camp/components/Map.tsx
src/components/templates/Camp/components/MapRoomOverlay.tsx

Fixes bug introduced in https://github.com/sparkletown/sparkle/pull/732

'Large Party Map' Performance - Part 3/x - FIX

---

src/pages/Admin/Admin.scss

**Note:** this PR targets master because it's an urgent blocking bug fix and staging isn't currently available.
When you were the admin of more venues than could fit on the screen, you were not able to scroll through the list. Now you can! 💅

[MASTER][BUGFIX] fix admin VenueList scrolling

---

src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
src/hooks/useConnectCurrentVenueNG.ts
src/hooks/useConnectRelatedVenues.ts
src/utils/id.ts
src/utils/reducers.ts
src/utils/selectors.ts

Sub-PR to https://github.com/sparkletown/sparkle/pull/747

[Sub-PR] Sub-PR to "Live schedule also includes parent, subvenue and sibling venue events"

---

src/components/molecules/MapPartygoerOverlay/MapPartygoerOverlay.tsx
src/components/molecules/MapRow/MapRow.tsx
src/components/molecules/UserProfilePicture/UserProfilePicture.tsx
src/components/templates/Camp/components/Map.tsx
src/components/templates/Camp/components/RoomList.tsx
src/components/templates/PartyMap/PartyMap.tsx
src/components/templates/PartyMap/components/Map/Map.tsx

fix a bunch of things that should make PartyMap and ThemeCamp Map way more performant!

---

src/components/molecules/ChatsList/ChatsList.scss
src/components/molecules/ChatsList/ChatsList.tsx
src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/VenuePartygoers/VenuePartygoers.tsx
src/components/molecules/VenuePartygoers/index.ts
src/components/templates/FireBarrel/FireBarrel.styled.ts
src/components/templates/PartyMap/components/Map/Map.scss
src/pages/Account/Account.scss
src/pages/Account/CodeOfConduct.tsx
src/pages/Account/Questions.tsx

- blue avatar + pulse
- Chatting with: indicator
- add chat drawer to other templates
- increase size of video in firebarrel
- show online burners at the top

add more party map fixes and tweaks

---

src/components/molecules/NavBar/NavBar.tsx

(eg. in Admin panel)
Also seemed to be some minor spacing related churn

ensure NavBar component doesn't render 'loading...' when no venue 

---

src/components/molecules/MessageList/MessageList.tsx
src/components/molecules/OnlineStats/OnlineStats.tsx
src/components/molecules/VenuePartygoers/VenuePartygoers.tsx
src/components/organisms/Chatbox/Chatbox.tsx
src/components/organisms/Room/Room.tsx
src/components/templates/Audience/Audience.tsx
src/components/templates/AvatarGrid/RoomModal.tsx
src/components/templates/FireBarrel/FireBarrel.tsx
src/components/templates/Jazzbar/components/ReactionList.tsx
src/components/templates/Playa/AvatarPartygoers.tsx
src/components/templates/Playa/Video/Room.tsx
src/components/templates/Playa/VideoChatLayer.tsx
src/types/Firestore.ts
src/utils/selectors.ts

Allow partygoers to be undefined

---

src/components/molecules/LiveSchedule/LiveEvent.tsx
src/components/molecules/LiveSchedule/LiveSchedule.tsx

Also renamed variables for consistency with live schedule

Make live events in sidebar clickable

---

src/components/molecules/VenuePartygoers/VenuePartygoers.tsx
src/types/Venue.ts

I really, really, really dislike the name headerTitle but I couldn't think of anything else, any other suggestions would be amazing.

add partygoers as default setting

---

src/components/templates/Camp/components/Map.scss
src/components/templates/Camp/components/Map.tsx

The grid-container was colliding with other styles on global level, now with the concrete name it won't.

fix camp names and join button width

---

src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/organisms/Room/Room.scss
src/components/organisms/Room/Room.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.scss
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx

Deploys:
- fix vertical icons and video size (#803)

deploy staging->master

---

src/components/organisms/Room/Room.scss
src/components/organisms/Room/Room.tsx
src/components/organisms/VideoModal/VideoModal.tsx
src/components/templates/ArtPiece/ArtPiece.scss
src/components/templates/ArtPiece/ArtPiece.tsx
src/components/templates/Audience/Audience.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.scss
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/pages/Admin/AdminVenuePreview.tsx
src/pages/SparkleSpaceMarketingPage/WelcomePage/WelcomePage.tsx
src/pages/VenueLandingPage/VenueLandingPage.tsx
src/pages/entrance/WelcomeVideo/WelcomeVideo.tsx
src/settings.ts

Deploys:
- Fix iframes (#811)
- Jazz bar layout fixes (#813)
- ⚡ Artpiece participant videos converted to grid layout (#817)

Deploy staging -> master

---

functions/venue.js
src/pages/Admin/Venue/Rooms/RoomDeleteModal.tsx

Fix room deletion

---

functions/venue.js
src/components/molecules/EventDisplay/EventDisplay.tsx
src/components/molecules/LiveSchedule/LiveEvent.tsx
src/components/organisms/AuthenticationModal/AuthenticationModal.scss
src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/pages/Admin/Venue/DetailsForm.tsx

* Only allow modifying owners via addVenueOwner and removeVenueOwner, since they are edited in a separate form
* Show venue name on schedules
* Make the login and register forms easier to use
* Clarify admin copy for parent ID feature

V-com fixes

---

src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/components/organisms/DateOfBirthField/DateOfBirthField.tsx
src/components/organisms/DateOfBirthField/index.ts
src/components/organisms/TicketCodeField/TicketCodeField.tsx
src/components/organisms/TicketCodeField/index.ts
src/settings.ts
src/types/forms.ts
src/utils/url.ts

Hack this in for now, we will make these proper venue features when the venue access is implemented.

Add ticket code and dob to form

---

src/pages/Admin/Venue/DetailsForm.tsx
src/settings.ts

This code has been extracted from the  following PR #822  Because it's needed for the event

allow party map background change

---

src/components/templates/Camp/components/MapRoomOverlay.tsx
src/components/templates/Camp/components/RoomCard.tsx
src/components/templates/PartyMap/components/Map/PartyMapRoomOverlay.tsx

Show/Hide room on the partymap/themecamp if it is Enabled/Disabled in the Admin panel

🐛 Room show/hide on map if enabled/disabled in admin panel

---

functions/venue.js
src/api/admin.ts
src/components/templates/ArtPiece/ArtPiece.tsx
src/components/templates/Camp/Camp.tsx
src/components/templates/PartyMap/PartyMap.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/types/Venue.ts

* Show toggle switch on admin form for Rangers support
* Show Rangers drawer on venue if enabled

✨ Show Rangers support toggle on admin form

---

src/pages/VenuePage/VenuePage.tsx

Co-authored-by: Chris Adams <chris@cadams.com.au>

Deploy 03122020

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/NavBar/playa.scss
src/components/molecules/NavSearchBar/NavSearchBar.tsx
src/components/molecules/Sidebar/Sidebar.scss
src/components/molecules/UserSearchBar/UserSearchBar.tsx
src/components/molecules/VenuePartygoers/VenuePartygoers.scss
src/components/molecules/VenuePartygoers/VenuePartygoers.tsx
src/components/organisms/UserProfileModal/UserProfileModal.scss
src/components/organisms/UserProfileModal/UserProfileModal.tsx
src/components/templates/PartyMap/components/Map/Map.scss
src/components/templates/PartyMap/components/Map/PartyMapRoomOverlay.tsx
src/scss/constants.scss
src/utils/url.ts

- increase navbar zindex to show it above schedule
- add new chatbox layout to private message modal
- add padding to number of partygoers online
- render room count conditionally to avoid rendering blue box
- open external internal links differently
This PR is pending on #845 and is going to have breaking changes + conflicts

party map layout fixes and tweaks

---

src/components/molecules/Footer/Footer.scss
src/components/molecules/Footer/Footer.tsx
src/components/organisms/AppRouter/AppRouter.jsx
src/components/organisms/WithNavigationBar/WithNavigationBar.scss
src/settings.ts

- Fixed to use the correct URLs based on whether it is Sparkle or Sparkleverse
- Added privacy policy link
- Improved styling
📷

Improve footer (add privacy policy, fix links, improve styling)

---

src/components/molecules/Footer/Footer.tsx
src/components/molecules/OnlineStats/OnlineStats.tsx
src/components/molecules/VenueInfoEvents/VenueInfoEvents.tsx
src/components/templates/Camp/components/MapRoomOverlay.tsx
src/settings.ts
src/utils/url.ts

- Make footer links open in new tab
- Make join links open in new tab

Always join rooms by opening a new tab

---

src/components/organisms/Room/Room.tsx
src/index.tsx
src/pages/Admin/AdminEditComponent.tsx
src/pages/Admin/AdminVenueRoomDetails.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx
src/utils/url.ts

Using `Bugsnag.notify` will give us visibility into issues that we would otherwise never see if they are only logged with `console.error`

Fix bug in utils/url isValidUrl and use Bugsnag.notify instead of console.error logging

---

functions/venue.js
src/api/admin.ts
src/components/molecules/Sidebar/Sidebar.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/Venue.ts

* Venue attendee title editable in venue create/edit
* Venue chat title editable in venue create/edit

Attendees and Chat labels configurable

---

functions/venue.js
src/api/admin.ts
src/components/templates/Audience/Audience.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/Venue.ts

Ability to set/edit seat column and row number when creating or editing a Auditorium venue

Auditorium editable seats by column and row

---

src/scss/global.scss

Requested by Thomas to make input errors more readable to users

Input error styled change to make it more readable

---

src/pages/VenueLandingPage/VenueLandingPage.tsx

This reverts commit d5b664dd63da7e71b1be7eaa4fc783c1a78d769b.
This has removed the button for all venues. Reverting to buy time to resolve the underlying logic/issue/etc

Revert "remove join event button when secret form is shown (#903)"

---

src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx

Fixes https://trello.com/c/23nBR4Af
The issue here is that we were setting the backend errors as a 'field level error', but it was only mapped to the `email` field. So if you got a backend error (eg. a password related error), and didn't change the `email` field (eg. because it was a password related error), then the backend error would never get cleared, and you would be unable to submit the form.
This would have blocked user signup/signin if they didn't try refreshing the page.
Fixed by treating it as a full custom error, and explicitly clearing it with `clearErrors` when any field in the form changes:
- https://react-hook-form.com/api#clearErrors
Note: this appears to have existed as a bug since the backend/'firebase' error type was introduced, so it's not a new issue:
- …

Ensure that backend errors on LoginForm / RegisterForm get cleared when form data changes

---

scripts/upload-table-config.ts

Allowed DRYing up of specifying what tables you want when you want a series of sequentially numbered tables.

Tweak table upload script

---

src/hooks/useUser.ts
src/pages/Account/Profile.tsx
src/pages/VenuePage/VenuePage.tsx
src/utils/profile.ts

* Prevent loops in account creation
* Pass the returnUrl
* More self-documenting code

Deploy - Prevent loops in account creation (#934)

---

.eslintrc

Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/48

Prevent importing all of firebase and thus a console warning

---

src/hooks/useConnectRelatedVenues.ts

Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/8

Fix error in flatMap occurring in some venues

---

src/components/organisms/Badges/Badges.tsx
src/pages/VenuePage/VenuePage.tsx

* Venues being saved to redux, from the VenuePage.jsx
* Filtering for badges done by visited.id and venue.name (visited.id is venue.name)

Show badges on profile modal

---

src/components/molecules/LiveSchedule/LiveEvent.tsx
src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/templates/AvatarGrid/RoomModal.tsx
src/utils/selectors.ts

This was preventing login for me

Guard against not yet loaded currentVenue

---

.circleci/config.yml

- https://create-react-app.dev/docs/production-build/#profiling

enable react profiling support in production

---

src/components/organisms/Chatbox/Chatbox.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx

as our templates are in use for more things now

Remove references to the band

---

src/components/organisms/Room/Room.tsx

Unknown video error is commonplace on Windows, and is confusing the users. This PR offers users some solutions.
partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/86

Slightly user friendlier unknown video error

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx

This should be the required configuration changes for setting up/deploying the `sparkle-2` environment.
Based on reviewing the code changes made in https://github.com/sparkletown/sparkle/pull/984 + the 'direct to branch' commits made following (which are collected together in https://github.com/sparkletown/sparkle/pull/989)

add configuration for sparkle-2 environment

---

.circleci/config.yml
.firebaserc
firebase.json
functions/index.js
src/index.tsx

Contents:
* add sparkle-3 to sparkle-10 environment configuration (#997)
* be more explicit with errors + show functions.config() (#1000)
This deploy should be the first green deploy on sparkle2.

Deploy sparkle2

---

public/index.html
public/robots.txt

Following instructions from:
* https://yoast.com/prevent-site-being-indexed/
* https://yoast.com/ultimate-guide-robots-txt/

Prevent indexing

---

scripts/clone-data-across-firebase-projects.ts
scripts/lib/helpers.ts

This script allows you to clone the specified venue(s) from one firebase project (eg. production) to another (eg. staging)

add scripts/clone-data-across-firebase-projects

---

src/index.tsx
src/polyfills.ts

Fixes flatmap error in Edge browser

---

package-lock.json
package.json
src/components/molecules/UserSearchBar/UserSearchBar.scss
src/components/molecules/UserSearchBar/UserSearchBar.tsx
src/index.tsx
src/polyfills.ts

Deploys:
- Fixes flatmap error in Edge browser (#1010)
- Sync sparkle1 -> staging (#993)
- Fixes chat position; Refactors chat component (#1009)

Deploy - flatMap and chat fixes, sync sparkle1

---

src/pages/VenueLandingPage/VenueLandingPage.tsx
src/types/Venue.ts

* :construction: If hostname is not same as redirectUrl, redirect user
* Removed newline

If hostname is not same as redirectUrl, redirect user (#1013)

---

src/components/organisms/ProfileModal/ProfilePopoverContent.scss
src/components/organisms/ProfileModal/ProfilePopoverContent.tsx

Remove previously set height and add fancy design for the scrollbar

make profile popover responsive

---

.circleci/config.yml
.firebaserc
firebase.json
scripts/upload-function-config-service-account.ts
src/index.tsx

Add the config settings for 2 new firebase environments.
Relates to https://github.com/sparkletown/internal-sparkle-issues/issues/169

Add 2 new firebase environments

---

src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/templates/ConversationSpace/ConversationSpace.scss
src/components/templates/Jazzbar/JazzBarSkeletonPage/JazzBarSkeletonPage.scss

Bug fixing for tomorrow's event Lingoda.
- Fixes position of user list avatars in conversation space and jazzbar.
- Add default avatar for user list when actual one is missing or can't be loaded.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/204
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/203

bug fixes and tweaks for lingoda

---

src/components/templates/PartyMap/PartyMap.tsx
src/components/templates/PartyMap/components/Map/Map.tsx

Profile fix

---

src/api/profile.ts
src/components/molecules/MapCell/MapCell.tsx
src/components/molecules/MapCell/index.ts
src/components/molecules/MapRow/index.ts
src/components/templates/PartyMap/components/Map/Map.tsx
src/components/templates/PartyMap/components/Map/hooks/useMapGrid.tsx

Performance improvement

---

package-lock.json
package.json

add axios to package.json for twilio

---

functions/package-lock.json
package-lock.json
package.json

add axios to functions

---

functions/package-lock.json
functions/package.json

add uuidv4 to functions

---

src/components/molecules/TableHeader/TableHeader.tsx
src/components/organisms/InformationLeftColumn/InformationLeftColumn.scss
src/components/templates/Jazzbar/JazzBarSkeletonPage/JazzBarSkeletonPage.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.scss
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/components/templates/Jazzbar/Jazzbar.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/Room.scss
src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/index.ts
src/components/templates/Jazzbar/components/JazzBarTableComponent/JazzBarTableComponent.scss
src/components/templates/Jazzbar/components/JazzBarTableComponent/JazzBarTableComponent.tsx
src/components/templates/Jazzbar/components/JazzBarTableComponent/index.ts

Jazzbar dirty css layout change

Jazzbar dirty css layout change [for Friday presentation purposes]

---

src/components/molecules/Footer/Footer.scss
src/components/molecules/TableHeader/TableHeader.tsx
src/components/organisms/Room/VideoErrorModal.tsx

Required by Thomas for today's event

Style changes

---

src/components/molecules/Footer/Footer.scss
src/components/molecules/TableHeader/TableHeader.tsx
src/components/organisms/Room/VideoErrorModal.tsx

* Change video error text
* Change table header styles

Style and text changes (#1144)

---

functions/venue.js
src/pages/Admin/Room/Modal/Item/Item.tsx

Creating a room was not working properly because of `showGrid` instead of `data.showGrid`
Also `editValues` always exist and the venue was always being created. Now the condition has been fixed and creating a room without venue is working.
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/315

Admin v2 - Fix room creation with venue and room url

---

src/components/molecules/Footer/Footer.scss
src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/organisms/Room/Participant.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx
src/scss/constants.scss

Fixes previously broken footer styles. Adds a few style tweaks to the reactions

Fixes styles for reaction in a table and footer-related

---

README.md
functions/venue.js
src/components/molecules/Footer/Footer.scss
src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/organisms/Room/Participant.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx
src/pages/Admin/Room/Modal/Item/Item.tsx
src/scss/constants.scss

Venue admin fixes; Reaction-related style fixes; Footer style fixes
Deploys:
- Update README.md (#1147)
- Admin v2 - Fix room creation with venue and room url (#1149)
- Fixes styles for reaction in a table and footer-related (#1153)

Deploy staging -> master: Venue admin fixes; Reaction-related style fixes; Footer style fixes

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/templates/PartyMap/components/Map/Map.scss
src/scss/constants.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/330
closes https://github.com/sparkletown/internal-sparkle-issues/issues/329

Fixes announcement bar styles

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss

Fixes scss-related css calc bug

Fixes scss-related css calc bug

---

src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/templates/Jazzbar/JazzTab/JazzTab.scss

Changes Reaction's z-index place + adds size to the user icon in Jazzbar
closes https://github.com/sparkletown/internal-sparkle-issues/issues/324

Changes Reaction's z-index place + adds size to the user icon in Jazzbar

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/molecules/TableHeader/TableHeader.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/328

Adds an unlocking clearing function on leave

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/molecules/TableHeader/TableHeader.tsx
src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/templates/Jazzbar/JazzTab/JazzTab.scss
src/components/templates/PartyMap/components/Map/Map.scss
src/scss/constants.scss

Banner -related style tweaks; Unlock room on user entry. Show full shoutout in Audience

Deploy staging => master; Banner -related style tweaks; Unlock room on user entry. Show full shoutout in Audience

---

src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx

Deploy 02112021

---

src/api/admin.ts
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts

The form validation was not passing because owners was a required field in the validation and it was not submitting the form.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/343

Admin - Fix for venue edit page in legacy admin

---

src/components/templates/PartyMap/components/Map/Map.tsx
src/utils/filter.ts

The rooms were always render without the isEnabled check in place. How this should work correctly.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/346

render rooms only when they are enabled

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/molecules/AnnouncementMessage/AnnouncementMessage.tsx
src/pages/VenuePage/TemplateWrapper.tsx

More info can been seen in the issue about the problem. The fix is pretty straightforward.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/348

add conditional banner centering

---

src/components/templates/PartyMap/components/RoomModal/RoomModal.scss

Fixes modal image sizing

---

src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/NavBar/playa.scss
src/components/molecules/NavSearchBar/NavSearchBar.scss
src/components/molecules/Sidebar/Sidebar.scss
src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
src/scss/constants.scss

Deploys:
- fix z-index layering issues with NavBar, LiveSchedule, and SideBar (#1172)

Deplo staging -> master (fix z-index layering issues)

---

src/pages/Admin/AdminEventModal.tsx

This fixes https://github.com/sparkletown/sparkle/issues/1054

fix to host name not appearing when editing event

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx
src/pages/Admin/AdminEventModal.tsx

Deploys:
- fix error in CircleCI when SLACK_ACCESS_TOKEN missing (#1185)
- fix to host name not appearing when editing event (#1182)
- Add 2 new firebase environments (#1188)

Deploy staging -> production

---

src/pages/Admin/Room/Edit/RoomEdit.styles.ts
src/pages/Admin/Room/Edit/RoomEdit.tsx

This fixes sparkletown/internal-sparkle-issues#393
Before
After

Fix admin edit buttons

---

src/components/organisms/ChatSidebar/components/PrivateChats/PrivateChats.tsx
src/hooks/privateChats.ts

Filteres self from online users
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/418

Fixes self chat issues

---

src/components/atoms/ChatMessage/ChatMessage.scss

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/419

Fixes chat message bubble styles

---

src/hooks/useVenueChat.ts

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/420

Allows message deletion for an admin

---

src/components/templates/Jazzbar/JazzTab/JazzTab.scss

Small jazzbar styling tweaks
@Sparkle-T asked to do so

Small jazzbar styling tweaks

---

src/components/templates/Jazzbar/JazzTab/JazzTab.scss

Changes iframe container height according to @Sparkle-T request

Changes iframe container height

---

src/components/templates/Jazzbar/JazzTab/JazzTab.scss

Staging => master deploy; Changes iframe container height (#1200)

Staging => master deploy; Changes iframe container height (#1200)

---

.github/labeler.yml
.github/workflows/labeler.yml

Automatically label pull requests based on the files changed.
This PR adds the `💎 styles` label when any `**/*.{css,scss,styles.ts}` files are changed in the PR.

Add `💎 styles` tag to auto labeler action workflow

---

src/components/templates/PartyMap/components/RoomAttendance.tsx
src/settings.ts

Something I was playing around with as part of a different PR/code review, figured it was worth committing.
While it's not currently used, since it is an optional prop that is defaulted, it also shouldn't cause any issues.

add optional maxVisible prop to RoomAttendance

---

.github/labeler.yml
functions/package-lock.json
functions/package.json
scripts/resize-images.ts
src/components/atoms/Button/Button.styles.ts
src/components/atoms/ImageInput/ImageInput.tsx
src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/components/molecules/AnnouncementMessage/AnnouncementMessage.tsx
src/components/molecules/Chatbox/Chatbox.tsx
src/components/molecules/ImageInput/ImageInput.tsx
src/components/molecules/NavBar/NavBar.scss
src/components/templates/PartyMap/components/RoomAttendance.tsx
src/pages/Account/Venue/VenueMapEdition/Container.tsx
src/pages/Account/Venue/VenueMapEdition/DraggableSubvenue.tsx
src/pages/Admin/Details/ValidationSchema.ts
src/pages/Admin/MapPreview/MapPreview.tsx
src/pages/Admin/Room/Edit/RoomEdit.tsx
src/pages/Admin/Room/Modal/Item/Item.tsx
src/pages/Admin/Venue/Details/VenueDetails.tsx
src/scss/constants.scss
src/settings.ts
src/utils/getLinkFromText.tsx

Deploy staging => master; Minor css + admin fixes

Deploy staging => master; Minor css + admin fixes

---

src/components/templates/PartyMap/components/Map/MapRoom.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/384

Adds shadow and pointer to a room

---

src/components/templates/Jazzbar/components/JazzBarTableComponent/JazzBarTableComponent.scss

Changes Jazzbar table styles

---

src/components/templates/Audience/Audience.scss
src/components/templates/Audience/Audience.tsx

Reverts sparkletown/sparkle#1231

Revert "fix Auditorium video container to be properly centred + some related cleanup"

---

src/utils/ConvertToEmbeddableUrl.tsx

Fixes an embed code for @Sparkle-T

Fixes an embed code

---

src/components/organisms/WithNavigationBar/WithNavigationBar.scss
src/components/templates/Audience/Audience.scss
src/components/templates/Audience/Audience.tsx
src/pages/Account/Account.scss
src/scss/constants.scss
src/scss/global.scss
src/utils/getLinkFromText.tsx

Deploy staging => master; Auditorium fixes

Deploy staging => master; Auditorium fixes

---

src/components/templates/PartyMap/components/RoomModalOngoingEvent/RoomModalOngoingEvent.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/497

Removes 'Live Schedule' text from RoomModal

---

src/components/templates/Audience/Audience.scss

Deploy the audience video bug fix for unesco

Deploy 08032021

---

src/components/organisms/EditProfileModal/EditProfileModal.tsx
src/components/organisms/ProfileModal/EditProfileForm/EditProfileForm.tsx
src/pages/Account/Profile.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/576

[ENV/KOTR] Changes placeholder text for partyname input

---

functions/venue.js
src/api/admin.ts
src/components/templates/Embeddable/Embeddable.scss
src/pages/Admin/Venue/TemplateForm.tsx
src/settings.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/505

Adds embedable UI to the admin panel

---

functions/venue.js
src/api/admin.ts
src/components/templates/Embeddable/Embeddable.scss
src/settings.ts

Deploys embedable UI to the admin panel (#1266)

Deploy staging => master

---

functions/venue.js
src/api/admin.ts
src/components/templates/Embeddable/Embeddable.scss
src/components/templates/PartyMap/components/Map/MapRoom.scss
src/settings.ts

Deploys embedable UI to the admin panel

Deploy master => env/kotr

---

firestore.rules
scripts/configure-venue-access.ts
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/pages/VenuePage/VenuePage.tsx
src/types/VenueAcccess.ts
src/types/venues.ts

Implementes emails access feature
closes https://github.com/sparkletown/internal-sparkle-issues/issues/570

Implementes emails access feature

---

firestore.rules
scripts/configure-venue-access.ts
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/pages/VenuePage/VenuePage.tsx
src/types/VenueAcccess.ts
src/types/venues.ts

- Implementes emails access feature (#1280)

Staging -> master deploy

---

firestore.rules
functions/access.js
src/api/auth.ts
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/types/venues.ts

(partially) closes https://github.com/sparkletown/internal-sparkle-issues/issues/588

Uses backend func to whitelist

---

src/components/atoms/ChatMessage/ChatMessage.scss
src/index.tsx

Fixes hyphens and sound effects

Fixes hyphens and sound effects

---

src/components/templates/Audience/Audience.scss

update Audience component styles
closes https://github.com/sparkletown/internal-sparkle-issues/issues/578

Fix retroactive review comments from sparkletown/sparkle#1249 RE: pointer-events in Audience component

---

src/components/molecules/AnnouncementMessage/AnnouncementMessage.scss
src/scss/constants.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/599

[BIGTOP ENV] Announcement banner color change

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx

partially closes https://github.com/sparkletown/internal-sparkle-issues/issues/598

Add new environment

---

src/pages/Admin/Venue/DetailsValidationSchema.ts

resolves https://github.com/sparkletown/sparkle/pull/1291#discussion_r602181401

Replace some validation alerts with more descriptive ones

---

scripts/bootstrap-new-environment.ts
scripts/lib/helpers.ts
scripts/update-admin-role-users.ts
src/types/venues.ts
src/utils/id.ts

This PR encodes some of the previously manual steps required to bootstrap a new firebase environment.
- add `scripts/bootstrap-new-environment.ts`
- add `scripts/update-admin-role-users.ts`
- some other little misc bits and pieces along the way

add scripts to assist with bootstrapping new environments

---

src/pages/Admin/Details/ValidationSchema.ts
src/pages/Admin/Venue/Rooms/RoomsValidationSchema.ts
src/utils/url.ts

closes: https://github.com/sparkletown/internal-sparkle-issues/issues/221
closes: https://github.com/sparkletown/internal-sparkle-issues/issues/9

Properly validate room urls to ensure they are valid, then remove our workaround

---

src/components/templates/Jazzbar/JazzTab/constants.ts

closes: https://github.com/sparkletown/internal-sparkle-issues/issues/625

Set 12 tables as default at Jazzbar

---

src/utils/url.ts

closes: https://github.com/sparkletown/internal-sparkle-issues/issues/9

Fix invalid URL

---

src/pages/Admin/Details/ValidationSchema.ts
src/pages/Admin/Venue/DetailsValidationSchema.ts

Increases the max char count
closes https://github.com/sparkletown/internal-sparkle-issues/issues/644

Increases the max char count

---

src/components/molecules/MapPartygoerOverlay/MapPartygoerOverlay.tsx
src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
src/components/molecules/UserProfilePicture/UserProfilePicture.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/655

Fix avatar position ‘jumping around’ when reactions used in Auditorium (v1)

---

scripts/lib/helpers.ts
scripts/upload-table-config.ts
src/components/molecules/TablesUserList/TablesUserList.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/components/templates/Jazzbar/JazzTab/constants.ts
src/utils/table.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/430
(**Edit by @0xdevalias:** Does this actually close this issue? Seems unrelated to me.. see questions in https://github.com/sparkletown/sparkle/pull/1326#pullrequestreview-635177059)

Refactor code to re-use our generateTables helper

---

src/components/templates/Auditorium/components/Section/Section.tsx
src/hooks/auditoriumSections.tsx
src/settings.ts

**Note:** This is a sub-PR that will be merged back into https://github.com/sparkletown/sparkle/pull/1251
This PR implements a more flexible way to set rows/columns for an auditorium.
closes https://github.com/sparkletown/internal-sparkle-issues/issues/558

[sub][new-auditorium] Flexible rows/colunns setting

---

src/pages/Admin/Venue/Rooms/RoomsForm.tsx

Fixes room edition

---

src/pages/Admin/AdminVenueRoomDetails.tsx
src/pages/Admin/MapPreview/MapPreview.tsx
src/pages/Admin/Room/Card/RoomCard.tsx
src/pages/Admin/Venue/Details/VenueDetails.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx

connected to https://github.com/sparkletown/sparkle/pull/1330 (see review comments in https://github.com/sparkletown/sparkle/pull/1330#pullrequestreview-637305519)

Unify types/values passed to upsertRoom/updateRoom in admin components

---

src/index.tsx

fix React warning about import of Loading component

fix React warning about import of Loading component

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx

related to https://github.com/sparkletown/internal-sparkle-issues/issues/666
Code changes accroding to https://github.com/sparkletown/internal-sparkle-issues/issues/186#issuecomment-781318065

Configures PA environment

---

src/components/organisms/Video/VideoParticipant.tsx
src/types/chat.ts

Cleans up User Profile Modal leftovers
**Edit by @0xdevalias**: Follow on from https://github.com/sparkletown/sparkle/pull/1155 to fix build issues introduced when merged: https://github.com/sparkletown/sparkle/pull/1155#issuecomment-830924521

fix staging + clean up User Profile Modal leftovers

---

src/components/atoms/Button/Button.tsx
src/components/atoms/Button/index.ts
src/components/templates/PosterHall/PosterHall.scss
src/components/templates/PosterHall/PosterHall.tsx
src/components/templates/PosterHall/components/PosterPreview/PosterPreview.scss
src/hooks/posters.ts
src/hooks/useDebounceSearch.ts
src/settings.ts

Given that the amount of posters in `posterhall` is expected to be > than 1600, we need a way to display the thing in an efficient & performant way

Initial approach on posterhall performance optimisation

---

src/components/atoms/Button/Button.tsx
src/components/atoms/Button/index.ts
src/components/templates/PosterHall/PosterHall.scss
src/components/templates/PosterHall/PosterHall.tsx
src/components/templates/PosterHall/components/PosterPreview/PosterPreview.scss
src/hooks/posters.ts
src/hooks/useDebounceSearch.ts
src/settings.ts

Deploys:
- Initial approach on posterhall performance optimisation (#1358)

Initial approach on posterhall performance optimisation (#1358)

---

functions/venue.js

While I was getting into the way events are saved/fetched, found this unused fn

remove unused legacy getVenueEvents backend function

---

src/types/Firestore.ts

Changes the way we use Array type

---

src/components/templates/ScreeningRoom/useScreeningRoom.ts

Fixes an error, I still don't fully understand why happens, but it was described in the stack overflow thread, linked in the comment

Fixes object freezing err

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx

Add the config settings for 4 new firebase environments.
partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/731
partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/780
partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/782
partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/784

Add 4 new environments: demo, unity, clever, burn

---

src/components/organisms/Video/VideoParticipant.scss
src/components/templates/PosterPage/PosterPage.tsx
src/components/templates/PosterPage/usePosterVideo.ts

adds user profile in PosterPage venue

Adds user profile in PosterPage venue

---

.circleci/config.yml
.firebaserc
firebase.json
src/index.tsx

partially closes https://github.com/sparkletown/internal-sparkle-issues/issues/804
partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/780

Configure burn staging envs

---

src/components/organisms/BannerAdmin/BannerAdmin.tsx

This update allows venue admin to enter a banner in multiline format - as well as using markdown format.

Multiline banner

---

.circleci/config.yml
.firebaserc
firebase.json
scripts/deploy-master-to-prod-envs
src/index.tsx

partially closes: https://github.com/sparkletown/internal-sparkle-issues/issues/797

add github environment

---

src/components/organisms/AppRouter/AppRouter.jsx
src/pages/Account/SamlSignIn.tsx
src/settings.ts

Initial approach, which seems incorrect as I couldn't make it work

[FIRST ATTEMPT/Probably incorrect] Adds SAML okta access

---

src/components/molecules/ScheduleEvent/ScheduleEvent.tsx

Fixes event modal popup bug when clicking on bookmark.

fix event modal popping up when clicking bookmark

---

src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx

Deploys:
- Feature/add home icon (#1536)

deploys staging -> master

---

src/components/atoms/UserAvatar/UserAvatar.tsx
src/components/molecules/NavSearchBar/NavSearchBar.tsx
src/pages/VenuePage/TemplateWrapper.tsx

Trying to fix performance for OHBM

Remove chat sidebar and users from the search bar

---

src/components/organisms/WithNavigationBar/WithNavigationBar.tsx
src/pages/VenuePage/TemplateWrapper.tsx

An possible fix of the error (`env/ohbm`): 
```
Error: <EventsProvider/> not found. Did you forget to include it in your component hierarchy?
```

[evn/ohbm] Add event provider to the WithNavigationBar

---

scripts/deploy-master-to-prod-envs

just to speed up the deployment process 🙃

add new prod branches to scripts/deploy-master-to-prod-envs

---

src/types/rooms.ts

[env/github] fix small bug in rooms.ts

---

functions/venue.js
src/components/molecules/NavBar/NavBar.tsx
src/components/templates/PartyMap/components/Map/MapRoom.tsx
src/components/templates/PartyMap/components/RoomModal/RoomModal.scss
src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
src/components/templates/PartyMap/components/RoomModalOngoingEvent/RoomModalOngoingEvent.scss
src/components/templates/PartyMap/components/RoomModalOngoingEvent/RoomModalOngoingEvent.tsx
src/components/templates/PartyMap/components/ScheduleItem/ScheduleItem.tsx
src/components/templates/Playa/VenuePreview.tsx
src/hooks/sounds.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/settings.ts
src/types/venues.ts

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/409
partially (in admin v1) fixes https://github.com/sparkletown/internal-sparkle-issues/issues/740
partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/715

add showSchedule toggle to admin v1 + clean up legacy showLiveSchedule + a few bonus bugfixes

---

src/pages/Account/Questions.tsx

partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/868

[env/github] change profile questions limit from 2 to 1

---

src/components/organisms/ProfileModal/UserInformationContent/UserInformationContent.tsx

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/872

[env/github] Make profile urls clickable

---

src/pages/Account/Login.scss

partly fixes https://github.com/sparkletown/internal-sparkle-issues/issues/868

[env/github] add purple border around octocat login button

---

src/components/organisms/ProfileModal/UserInformationContent/UserInformationContent.tsx

no issue created for this - removes profile links from the profile modal

[env/github] remove profile links from profile

---

src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx
src/components/organisms/AuthenticationModal/InitialForm/InitialForm.scss
src/components/organisms/AuthenticationModal/InitialForm/InitialForm.tsx
src/pages/Account/Account.scss
src/pages/Account/Login.scss
src/pages/Account/Login.tsx
src/pages/Account/Profile.tsx

based on @whoaitsaimz's comments in https://github.com/sparkletown/sparkle/pull/1693 (https://github.com/sparkletown/sparkle/pull/1693#issuecomment-870869218 + https://github.com/sparkletown/sparkle/pull/1693#issuecomment-870871005)
partly fixes sparkletown/internal-sparkle-issues#868

[env/github] update registration page again

---

src/pages/Account/Profile.tsx

Does what https://github.com/sparkletown/sparkle/pull/1700 ought to do
(Change the name in the welcoming message)

[env/github] Replaces github handle with firstName in the welcoming message

---

src/settings.ts

requested by @whoaitsaimz in slack - no github issue

[env/github] change default url to in/register

---

src/hooks/users/index.ts
src/hooks/users/useConnectWorldUsers.ts
src/hooks/users/useRecentLocationUsers.ts
src/hooks/users/useRecentVenueUsers.ts
src/hooks/users/useRecentWorldUsers.ts
src/hooks/users/useWorldUsers.ts
src/hooks/users/useWorldUsersById.ts

Refactored `hooks/users.ts` into individual files within `hooks/users/*`

refactor hooks/users.ts into individual files within hooks/users/*

---

src/scss/customOverrides.scss

Override time on Sparkle & venues visited

---

scripts/add-auditorium-sections.ts

* Created a script for bulk creation of auditorium sections

created script for bulk creation of auditorium sections

---

src/utils/schedule.ts

fix for https://github.com/sparkletown/internal-sparkle-issues/issues/884#issuecomment-875165878

fixed alphabetical sorting if number is used

---

src/components/organisms/RenderMarkdown/RenderMarkdown.tsx

Fixes chat display
closes https://github.com/sparkletown/internal-sparkle-issues/issues/892

Fixes chat display

---

src/hooks/users/index.ts
src/pages/Admin/Admin.tsx

Adds the worlds users provider to admin v1 to fix 💣 This will need to be added in v3 as well but there are multiple pages there and needs more thought.

add WorldUsersProvider to admin v1

---

src/api/admin.ts
src/components/templates/TalkShowStudio/components/Audience/Audience.tsx
src/hooks/useStage.ts
src/types/User.ts

Fixes merge conflicts so that GitHub can build

Fixes the merge conflicts

---

src/components/molecules/NavBar/NavBar.tsx
src/components/templates/Auditorium/components/AllSectionPreviews/AllSectionPreviews.tsx
src/components/templates/Auditorium/components/Section/Section.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx

Return to the state of things before my refactor PR

[env/github] Change all back button text to `Back`

---

src/components/templates/ConversationSpace/ConversationSpace.scss

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/894

Add padding to conversation space top

---

src/pages/VenueLandingPage/VenueLandingPage.tsx

fix Error: `<WorldUsersProvider/>` not found in `VenueLandingPage` that was introduced in https://github.com/sparkletown/sparkle/pull/1703
partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/839

fix Error: <WorldUsersProvider/> not found in VenueLandingPage + some associated tech debt

---

src/components/templates/Auditorium/components/Section/Section.scss

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/901

Fixes the sizes of the seats

---

src/pages/Account/Login.tsx
src/settings.ts

Fixed sparkletown/internal-sparkle-issues#880

AAU Added defaultCustomAuthConfig 

---

src/components/organisms/EditProfileModal/EditProfileModal.tsx
src/components/organisms/ProfileModal/EditProfileForm/EditProfileForm.tsx
src/components/organisms/ProfileModal/UserInformationContent/UserInformationContent.tsx
src/components/organisms/UserProfileModal/UserProfileModal.tsx
src/pages/Account/Questions.tsx
src/pages/Admin/EntranceExperience/EntranceExperience.tsx
src/pages/Admin/EntranceExperience/EntranceExperience.types.ts
src/pages/AdminAdvancedSettings/AdminAdvancedSettings.tsx

Fixed sparkletown/internal-sparkle-issues#881

AAU added sovereignVenue for profileQuestions

---

.circleci/config.yml
.firebaserc
firebase.json
scripts/deploy-master-to-prod-envs
src/index.tsx

partially closes https://github.com/sparkletown/internal-sparkle-issues/issues/808

Add configuration for a new environment

---

src/settings.ts

Adds new auditorium to the settings to fix the visibility issue(for the admins)

Adds new auditorium to the settings

---

src/pages/Admin/Venue/DetailsForm.tsx

Fixes the sovereign venue update issue

Fixes the sovereign venue update issue

---

README.md
docs/bootstrap-application.md
docs/create-new-environment.md
docs/firebase-emulators.md
docs/getting-started.md
docs/start-application.md
docs/stripe-configuration.md
docs/twilio-configuration.md

Sub-PR to #1611 
* Split readme steps into files at /docs
* Added missing info on bootstrap scripts/firebase setup/application launch
* minor formatting

[sub-PR] Split readme into various steps at /docs + updated info on bootstrap

---

src/components/molecules/NavBar/NavBar.tsx
src/pages/Admin/Admin.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx

Admin v1 shows the `BackButton` in the `NavBar` which isn't supposed to.
This PR adds `hasBackButton={false}` for the Admin v1 use cases.

hide back button in NavBar within admin panel

---

src/components/atoms/ChatMessage/ChatMessage.scss
src/components/organisms/ChatSidebar/components/OnlineUser/OnlineUser.scss

Adds conditional/lazy loading for long lists

Adds conditional/lazy loading for long lists

---

src/components/atoms/UserAvatar/UserAvatar.scss
src/scss/constants.scss

Fixes the reaction layering.
This regression was  introduced by `nametag` PR https://github.com/sparkletown/sparkle/pull/1049

Removes z-index from the avatar

---

src/utils/url.ts

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/916

fix event modal url: remove all the spaces in the URL

---

src/types/reactions.ts

removed ghost and piano emoji
https://doesitsparkle.slack.com/archives/C0229C1EC86/p1626118567002800

removed ghost and piano emoji

---

src/pages/Account/CodeOfConduct.tsx
src/pages/Account/Questions.tsx

fixed undefined question length const
Occurs after registration on venues with questions ( possibly )

fixed undefined question length const

---

src/components/molecules/Footer/Footer.tsx
src/settings.ts

Slack convo: https://doesitsparkle.slack.com/archives/C0229C1EC86/p1626075892397900
[env/github] changed footer url link to sparklespaces

[env/github] changed footer url link to sparklespaces

---

src/components/molecules/ChatMessageBox/ChatMessageBox.tsx
src/components/molecules/Chatbox/Chatbox.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/918
Thread reply state now resets after sending a message to a thread

fixed thread reply state reset after sending a message

---

docs/bootstrap-application.md
docs/create-new-environment.md
docs/firebase-emulators.md
docs/getting-started.md
docs/twilio-configuration.md

Cleaned up some of the docs a bit. Follow on from:
- https://github.com/sparkletown/sparkle/pull/1611
partially closes sparkletown/internal-sparkle-issues#778

cleanup docs a bit + fix some broken links

---

package-lock.json
package.json

update date fns from 2.21.1 to 2.22.1

bump date fns from 2.21.1 to 2.22.1

---

src/components/molecules/UserList/UserList.tsx
src/components/templates/Auditorium/components/SectionPreview/SectionPreview.tsx
src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
src/components/templates/Playa/VenuePreview.tsx
src/components/templates/ReactionPage/ReactionPage.tsx

add clickable avatars to RoomModal.

add clickable avatars to RoomModal

---

src/settings.ts

increase loc update for user location

[env/github] increase loc update for user location

---

src/components/atoms/UserAvatar/UserAvatar.tsx
src/components/organisms/WithNavigationBar/WithNavigationBar.tsx
src/components/templates/Audience/Audience.tsx
src/components/templates/PartyMap/components/Map/Map.tsx
src/hooks/auditorium/useAuditoriumSection.ts
src/hooks/useUser.ts
src/hooks/users/useRecentLocationUsers.ts
src/hooks/users/useRecentWorldUsers.ts
src/hooks/users/useWorldUserLocation.tsx
src/hooks/users/useWorldUsers.tsx
src/hooks/users/useWorldUsersById.ts
src/index.tsx
src/pages/VenuePage/TemplateWrapper.tsx
src/store/actions/Cache.ts
src/store/actions/index.ts
src/store/reducers/Cache.ts
src/store/reducers/index.ts
src/types/Firestore.ts
src/utils/selectors.ts

[env/github] nuclear users cache fix

---

src/hooks/users/useWorldUsers.tsx
src/pages/VenuePage/TemplateWrapper.tsx

[env/github] Fix/remove useconnect

---

src/pages/VenuePage/TemplateWrapper.tsx

[env/github] returns chat

---

src/components/templates/Auditorium/components/SectionPreview/SectionPreview.scss

Improves section visuals

---

src/components/templates/ScreeningRoom/ScreeningRoom.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/936

add margin to load more btn in ScreeningRoom

---

scripts/add-screening-room-videos.ts

help to close https://github.com/sparkletown/internal-sparkle-issues/issues/924

add screening room addition script

---

src/pages/Admin/Admin.tsx
src/pages/Admin/AdminVenuePreview.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx
src/pages/Admin/VenueList/VenueList.tsx
src/utils/address.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/711
Replaced outdated `camp` references with `space` ones

replaced camp references with space

---

src/api/admin.ts
src/components/templates/Playa/Playa.tsx
src/components/templates/Playa/PlayaVenue.tsx
src/pages/Account/Venue/VenueMapEdition/Container.tsx
src/pages/Account/Venue/VenueMapEdition/PlayaContainer.tsx
src/pages/Admin/Admin.tsx
src/pages/Admin/AdminVenuePreview.tsx
src/pages/Admin/Details/ValidationSchema.ts
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/venues.ts
src/utils/venue.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/710
removed jam icon references throughout codebase + fixed related comments from https://github.com/sparkletown/sparkle/pull/1381

removed jam icon references

---

src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx
src/pages/Account/Account.scss

related https://github.com/sparkletown/internal-sparkle-issues/issues/887
Update the profile picture page

update Accessibility of Profile picture picker

---

src/pages/Account/Questions.scss

Styling tweak to expand the Questions properly

fixes the Questions display, if there are a lot of questions

---

src/components/molecules/ImageInput/ImageCollectionInput.tsx

A different PR of mine had a bug- forgot to import a setting. This fixes it

Fix import bug in ImageCollectionInput

---

src/components/atoms/ChatMessage/ChatMessage.scss
src/components/molecules/MapPartygoerOverlay/MapPartygoerOverlay.scss

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/937
Commented out certain css code that caused gpu being overused

commented out performance burning code

---

functions/venue.js
src/settings.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/798

add screening room admin option

---

src/components/organisms/EventModal/EventModal.tsx

Re-closes https://github.com/sparkletown/internal-sparkle-issues/issues/947
Fixed comments as per https://github.com/sparkletown/sparkle/pull/1895#discussion_r675654867

improved fix of schedule event redirect

---

src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
src/utils/userLocation.ts

Refactors GA analytics

---

src/pages/Account/Login.scss
src/pages/Account/Login.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/887

Wrapping into button

---

src/pages/Account/Login.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/887

[env/github] fixes accessibility concerns for login

---

src/pages/Admin/EventsComponent.tsx
src/pages/Admin/VenueEventDetails.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/953
Restored edit/delete logic for events

Restored edit/delete event buttons

---

src/components/molecules/ImageInput/ImageCollectionInput.tsx
src/pages/Admin/Venue/DetailsForm.tsx
src/pages/VenueLandingPage/VenueLandingPage.scss
src/scss/global.scss

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/729

Make image logo input circular

---

src/components/atoms/Checkbox/Checkbox.scss

adds min height/width + proper position to a toggler

---

src/pages/VenueLandingPage/VenueLandingPage.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/963
* added minutes to the event preview component
* replaced old time transform logic with helpers

added minutes to event preview component

---

src/settings.ts

closes: sparkletown/internal-sparkle-issues#955

BM Admin Adjustments: available venues, orders & descriptions

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.scss
src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
src/components/molecules/ScheduleItemNG/index.ts
src/components/molecules/ScheduleNG/ScheduleNG.scss
src/components/molecules/ScheduleNG/ScheduleNG.tsx
src/components/molecules/ScheduleNG/index.ts
src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
src/components/organisms/NavBarSchedule/utils.ts
src/scss/constants.scss
src/utils/event.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/980
Working example: https://co-reality-staging--preview-pr-1937-wu61whvt.web.app/in/mypartymap

Schedule3: Chronological list of experiences

---

src/pages/Admin/BackgroundSelect/BackgroundSelect.scss
src/pages/Admin/BackgroundSelect/BackgroundSelect.tsx
src/scss/constants.scss

closes issue https://github.com/sparkletown/internal-sparkle-issues/issues/982

Admin V3 - fix comments regarding space for default maps

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.scss
src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
src/components/molecules/ScheduleNG/ScheduleNG.tsx
src/components/organisms/NavBarSchedule/NavBarSchedule.scss
src/components/organisms/NavBarSchedule/NavBarSchedule.tsx

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/991

[schedule 3.0] add bookmarking feature

---

.eslintrc
package-lock.json
package.json
scripts/add-event.js
scripts/clear-chat.js
scripts/config-upload.js
scripts/update-member-emails.js
scripts/upload-to-storage.js
src/components/molecules/Chatbox/useTriggerScrollFix.tsx
src/components/organisms/AdminVenueView/components/VenueRoomsEditor/VenueRoomsEditor.tsx
src/components/organisms/Room/LocalParticipant.tsx
src/components/organisms/Room/Room.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx
src/components/templates/Playa/AvatarLayer.tsx
src/components/templates/Playa/VenuePreview.tsx
src/components/templates/Playa/Video/Room.tsx
src/pages/Account/Venue/VenueMapEdition/Container.tsx
src/pages/Account/Venue/VenueMapEdition/CustomDragLayer.tsx
src/pages/Account/Venue/VenueMapEdition/DraggableSubvenue.tsx
src/pages/Account/Venue/VenueMapEdition/snapToGrid.ts
src/pages/Admin/Venue/Details/VenueDetails.tsx
src/polyfills.ts
src/serviceWorker.ts
src/store/api/worldUsers.ts
src/utils/time.ts
src/validation.js

As we don't use `funcion` declarations and expressions I propose to enforce that in eslint.

Eslint rule for using only arrow functions

---

.github/workflows/update-env-branches.yml

Adds gitHub action push script to update another branch on staging push

Adds gitHub action push script

---

.github/workflows/update-env-branches.yml

Fix/GitHub actions script to work with master

Fixes GitHub actions script

---

.github/workflows/update-env-branches.yml

deploy master -> staging

---

src/components/organisms/AdminVenueView/AdminVenueView.scss
src/components/organisms/AdminVenueView/AdminVenueView.tsx

fixed sparkletown/internal-sparkle-issues#988

Admin V3 - Fixed header text alignment and missing icons

---

src/pages/Admin/BackgroundSelect/BackgroundSelect.scss

when we hover it moves the maps so it fixed in this PR.
closes https://github.com/sparkletown/internal-sparkle-issues/issues/982

Admin V3 -- fix hover on maps defaults

---

.github/workflows/update-env-branches.yml

On push to master, deploy the change to all of the production envs except for the one with the custom code

Adds all branches to ci/cd

---

src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
src/types/venues.ts
src/utils/event.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/997
* added venue sorting by orderPriority including start time / duration
* covers both positive and negative orderPriority values

Added venue sorting by orderPriority

---

functions/auth.js

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1018
I added new twillio config to the staging functions config. Need to redeploy it now
Redeploy the functions

Redeploy the functions

---

src/components/templates/Embeddable/Embeddable.tsx
src/settings.ts

This is a combination of two PRs on `env/github`. 
Details here: https://github.com/sparkletown/internal-sparkle-issues/issues/662#issuecomment-899621263

Iframe flags fix for Embeddable

---

src/settings.ts

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1041

[env/burn] change default redirect url

---

functions/venue.js
src/api/admin.ts
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/rooms.ts
src/types/venues.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1068

BM: make description/subtitle not required

---

functions/venue.js
src/api/admin.ts
src/pages/Admin/Venue/DetailsValidationSchema.ts
src/types/rooms.ts
src/types/venues.ts

Reverts sparkletown/sparkle#2009

Revert "BM: make description/subtitle not required"

---

src/components/templates/AnimateMap/hooks/useArtcars.ts
src/components/templates/AnimateMap/hooks/useFirebarrels.ts
src/types/Firestore.ts
src/types/animateMap.ts
src/utils/selectors.ts

partially related to https://github.com/sparkletown/internal-sparkle-issues/issues/940

Adds storage for Artcars and Firebarrels

---

.github/workflows/update-env-branches.yml

As per the discussion with the product owners, we want to speed up the deployment process for Burn env

Disable deployment for some envs

---

src/components/templates/AnimateMap/bridges/DataProvider/CloudDataProvider.ts

Normalizing coefficient removed

fix coordinate for rooms

---

src/components/organisms/NewProfileModal/components/header/ProfileModalAvatar/ProfileModalAvatar.tsx

Resolve:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1094

[env/burn-staging] Fix upload avatar 

---

src/components/organisms/ChatSidebar/ChatSidebar.scss
src/components/organisms/ChatSidebar/ChatSidebar.tsx
src/hooks/chats/chatSidebar.ts

Resolve:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1006

[env/burn-staging] split private chat and venue chats

---

src/pages/VenuePage/TemplateWrapper.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1096

[env/burn-staging] Removes back button for animate map

---

src/components/organisms/ChatSidebar/components/PrivateChats/PrivateChats.tsx

This is a follow-up to https://github.com/sparkletown/sparkle/pull/2041 resolving  https://github.com/sparkletown/sparkle/pull/2041#discussion_r693941170 and  https://github.com/sparkletown/sparkle/pull/2041#discussion_r693990477

Wrapps with `useCallback` a fn

---

src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx

Adds new default mapings for room-venue modal

Adds correct room-venue default mappings

---

src/pages/Admin/MapPreview/MapPreview.scss
src/pages/Admin/MapPreview/MapPreview.tsx

Resolve:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1101

[ emv/burn-staging ] Add map zoom

---

src/components/molecules/ScheduleVenueDescription/ScheduleVenueDescription.scss
src/components/molecules/ScheduleVenueDescription/ScheduleVenueDescription.tsx
src/components/organisms/NavBarSchedule/NavBarSchedule.scss
src/components/organisms/NavBarSchedule/NavBarSchedule.tsx

Resolve:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1002

[env/burn-staging] Feature/add sidenav bar

---

functions/access.js
scripts/configure-venue-access.ts
src/api/auth.ts
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx

Adds code whitelisting

---

scripts/configure-venue-access.ts

Adds better emails/venues access

Adds better emails/venues access upload

---

src/components/templates/AnimateMap/bridges/DataProvider/CloudDataProvider.ts

critical performance fix

---

src/components/templates/AnimateMap/components/Shoutouter/Shoutouter.scss
src/components/templates/AnimateMap/components/Shoutouter/Shoutouter.tsx
src/components/templates/AnimateMap/game/map/systems/BubbleSystem.ts

refactor component as react-like style
fix null exception

fix and refactor shoutouter

---

src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx
src/components/organisms/InformationLeftColumn/InformationLeftColumn.scss
src/pages/Admin/Venue/VenueWizard.tsx
src/scss/constants.scss

disabled schedule `whats on` btn on /admin/create route

disabled schedule on venue create

---

src/components/organisms/NavBarSchedule/NavBarSchedule.scss

Fixes schedule height and padding. Fixes download buttons positioning

[env/burn-staging] Fixes schedule height and padding. Fixes download buttons positioning

---

src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.scss
src/components/templates/Jazzbar/components/JazzBarRoom/Room.scss
src/scss/global.scss

Fixes too big avatars in video component

Fixes too big avatars in video component

---

src/components/templates/AnimateMap/components/Shoutouter/Shoutouter.scss
src/components/templates/AnimateMap/components/UIOverlayGrid/UIOverlayGrid.scss

fix shoutouter styles

---

src/components/templates/AnimateMap/bridges/DataProvider/Contructor/PlayerIO/ServersideDLL/Serverside Code/RoomS/Game.cs
src/components/templates/AnimateMap/game/GameInstance.ts

fix receive from playerio initial position

fix initial position

---

src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx
src/components/organisms/AnimateMapOnboardFlow/AnimateMapOnboardFlow.tsx
src/pages/RegistrationFlow/InitialFormRF/InitialFormRF.tsx
src/pages/RegistrationFlow/RegisterFormRF/RegisterFormRF.tsx
src/settings.ts

detailed in https://docs.google.com/presentation/d/1wYUbuC6_7UhrJNOivh5pa9rOrsecn9_6VvSt1yq7mfQ/edit#slide=id.gec46292126_0_103
fixes everything except profile questions and last slide

[env/burn-staging] minor registration flow tweaks

---

src/components/molecules/NavBar/NavBar.scss
src/components/molecules/NavBar/NavBar.tsx
src/components/molecules/NavSearchBar/NavSearchBar.scss

NavBar:
* hide time on playa and burners count on mobile
* add button "simplified view" to the navbar

[BM] navbar adaptive adjustments + simplified view button

---

src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.scss
src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.tsx

change firebarrel videochat leave button

change firebarrel videochat leave button

---

src/components/templates/AnimateMap/game/map/MapContainer.ts

exit firebarrel fix

---

functions/openweathermap.js

fixes import; makes it relative as we do that in other files

Fix broken functions js import

---

src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.scss
src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.tsx
src/components/templates/AnimateMap/components/UIOverlay/UIOverlay.scss

update Firebarrel's Leave button

---

src/components/templates/AnimateMap/bridges/CloudDataProviderWrapper.tsx
src/components/templates/AnimateMap/bridges/DataProvider/CloudDataProvider.ts
src/components/templates/AnimateMap/bridges/DataProvider/Contructor/PlayerIO/PlayerIOBots.ts
src/components/templates/AnimateMap/bridges/DataProvider/Contructor/PlayerIO/PlayerIODataProvider.ts
src/components/templates/AnimateMap/bridges/DataProvider/Contructor/PlayerIO/RoomOperator/PlayerIOSeparatedRoomOperator.ts
src/components/templates/AnimateMap/game/GameInstance.ts
src/types/venues.ts

throw venue firestore data for customize playerio

add playerio remote setting

---

src/pages/RegistrationFlow/InitialFormRF/InitialFormRF.tsx

detailed in https://doesitsparkle.slack.com/archives/C016K256UCF/p1630340900330000?thread_ts=1630213642.231900&cid=C016K256UCF

[env/burn-staging] change 'buy tickets' to 'get a ticket'

---

src/components/organisms/ChatSidebar/ChatSidebar.scss
src/components/organisms/ChatSidebar/ChatSidebar.tsx
src/components/organisms/HelpCenter/components/HelpCenterContent/HelpCenterContent.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1127

Add Create button on Playa

---

functions/openweathermap.js
src/api/openweathermap.ts
src/components/molecules/NavBarScheduleWeather/NavBarScheduleWeather.tsx

Follows up https://github.com/sparkletown/sparkle/pull/2092
@sofisparkle requested a change to imperial units

Weather in schedule: change units to imperial

---

src/pages/Admin/Venue/Rooms/RoomsForm.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1120
The change affects only AdminV1 as for AdminV3 it seems unnecessary.

Default room URL: made it to point to the venue

---

src/settings.ts

A way to avoid code like this:
- https://github.com/sparkletown/sparkle/pull/2162/files#r699188622
Rationale:
- https://github.com/sparkletown/sparkle/pull/2162#discussion_r698505700

Add always empty/noop values

---

src/components/molecules/ScheduleEventListNG/ScheduleEventListNG.scss
src/components/molecules/ScheduleEventListNG/ScheduleEventSubListNG.tsx

Resolve issue :
- https://github.com/sparkletown/internal-sparkle-issues/issues/1137

[env/burn-staging] Add local time text

---

src/components/molecules/NavBar/NavBar.tsx

Resolve issue:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1136

[env/burn-staging] Topbar Elements Swap

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
src/settings.ts

Fixes event URLs
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1134
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1135

Fix event links in the schedule

---

src/pages/Admin/Venue/DetailsForm.tsx

detailed in https://github.com/sparkletown/sparkle/pull/2049#issuecomment-905556485
fixes sparkletown/internal-sparkle-issues#1078

[env/burn-staging] add default video for embeddable and jazzbar templates

---

src/pages/Admin/Venue/Rooms/RoomsForm.tsx

fixes for sparkletown/internal-sparkle-issues#1123

Fixed BM Flashes of 404 screen on Admin panel 

---

src/components/templates/AnimateMap/game/map/entities/createVenueEntity.ts
src/store/reducers/AnimateMap.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1138

BM: Dim empty and not live venues on the playa

---

src/components/templates/AnimateMap/game/map/entities/createFirebarrelEntity.ts

increase firebarrel bubbles timeout

---

src/pages/EmergencyViewPage/EmergencyViewPage.scss

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1158

emergency view background filter increased

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.scss
src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1151

Schedule: adds 'until' to endDate and a hyphen after startDate

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1135

Make event venue clickable

---

src/pages/Admin/Admin.scss
src/pages/Admin/Admin.tsx
src/settings.ts

closes sparkletown/internal-sparkle-issues#1141

BM Added Creator Help link to creation tools

---

src/pages/Admin/Venue/DetailsForm.tsx

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1078

[env/burn-staging] make embeddable field editable again

---

src/components/atoms/ImageInput/ImageInput.tsx
src/components/molecules/ImageInput/ImageInput.tsx
src/pages/Admin/Venue/VenueWizard/redux/reducer.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1077
Fixes AdminV1 as well as AdminV3
This also fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1156

Fixes default banner and logo

---

src/components/atoms/ChatMessage/ChatMessage.scss
src/components/molecules/NavSearchBar/NavSearchBar.scss
src/components/molecules/Schedule/Schedule.scss
src/components/organisms/NavBarSchedule/NavBarSchedule.scss
src/components/templates/ArtPiece/ArtPiece.scss
src/components/templates/PartyMap/PartyMap.scss
src/components/templates/PartyMap/components/RoomModal/RoomModal.scss
src/pages/Admin/Admin.scss
src/pages/Admin/Admin.styles.ts
src/pages/Admin/Venue/Venue.scss
src/pages/EmergencyViewPage/EmergencyViewPage.scss
src/scss/constants.scss
src/scss/global.scss

Consolidation of the scrollbar styles use. Now only once set for * (which can easily be overridden in the respective components) and unifying for webkit and standard as well.

Use one scrollbar style

---

src/components/organisms/NavBarSchedule/NavBarSchedule.tsx

Resolve issue:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1002#issuecomment-911915629

[env/burn-staging] Update show only events in that venue by default 

---

src/components/templates/PartyMap/components/Map/MapRoom.scss

Resolve issue:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1159
Before:
After:

Fix Unclickable rooms UI

---

src/components/templates/ExternalRoom/ExternalRoom.tsx

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1140
specifically https://github.com/sparkletown/internal-sparkle-issues/issues/1140#issuecomment-912783682

[env/burn-staging] fix external link opening and user count

---

src/components/templates/AnimateMap/game/constants/StubData.tsx

Caranirvana Art Car: fix link

---

src/components/templates/AnimateMap/game/constants/StubData.tsx

Deploy staging -> master (artcar link fix)

---

firestore.rules
src/hooks/useSettings.ts
src/pages/VenuePage/TemplateWrapper.tsx
src/settings.ts
src/types/Firestore.ts
src/types/settings.ts
src/utils/selectors.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1169

Add the ability to hide the chat from firestore

---

src/pages/VenuePage/VenuePage.tsx

Tries to resolve:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1088
by updating the check of field `entrance` from `isDefined()` to `Array.isArray(entrance) && entrance.length > 0`
Based on comment https://github.com/sparkletown/internal-sparkle-issues/issues/1088#issuecomment-913609828

Update entrance field check in VenuePage

---

src/pages/Admin/Venue/DetailsForm.tsx
src/pages/Admin/Venue/DetailsValidationSchema.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1071
Regarding: https://github.com/sparkletown/internal-sparkle-issues/issues/1071#issuecomment-912844826
Removed toggler from UI

Disable jukebox UI toggle button ( burn )

---

src/scss/constants.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1165

fixed navbar stacking context

---

functions/venue.js

Fix venue function

---

src/hooks/useRoom.ts

Fixes reload on every room entry

Fixes reload on every room entry

---

src/pages/Admin/Venue/Rooms/RoomsForm.tsx

Quick fix for missing field due to PR regression

Add   title: values.title in RoomsForm

---

src/components/templates/AnimateMap/components/FirebarrelWidget/FirebarrelWidget.scss

- closes https://github.com/sparkletown/internal-sparkle-issues/issues/1054
After:

Fix Mobile Video Optimisation

---

src/components/templates/PartyMap/PartyMap.tsx

Resolve issue:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1147

[env/burn-stagin] Update events shown in modal

---

functions/world.js
src/components/molecules/NavBar/NavBar.tsx

Fixes build errors

---

src/utils/venue.ts

Fixes fetch bug

---

src/components/organisms/NavBarSchedule/NavBarSchedule.tsx

Fix for crashing https://staging.sparkle.space/in/buttparties

Fix NavBarSchedule negative dayDifference crash

---

src/components/organisms/AdminVenueView/components/RunTabUserInfo/RunTabUserInfo.tsx

Fixes build errors in staging.

ChatUser build fix

---

src/components/molecules/LoadingPage/LoadingPage.scss
src/components/organisms/HelpCenter/HelpCenter.scss
src/components/organisms/HelpCenter/HelpCenter.tsx
src/components/organisms/RenderMarkdown/RenderMarkdownInner.tsx
src/scss/constants.scss

сlosed sparkletown/internal-sparkle-issues#1153

BM Add back button to help pages

---

src/components/molecules/UserList/UserList.scss
src/components/molecules/UserList/UserList.tsx
src/components/templates/Auditorium/components/SectionPreview/SectionPreview.tsx
src/components/templates/ConversationSpace/ConversationSpace.tsx
src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
src/components/templates/PosterPage/PosterPage.tsx
src/components/templates/ReactionPage/ReactionPage.tsx
src/types/auditorium.ts

Fixes users list component. Before that it incorrectly showed the number of users in the users list component

Fixes users list component

---

src/components/organisms/AdminVenueView/AdminVenueView.tsx

Remove photobooth button from admin

---

src/pages/Admin/Venue/VenueDetailsSubForm.tsx
src/settings/index.ts
src/settings/sectionSettings.ts

Fix section settings

---

functions/package.json
functions/triggered.js

Removes optional chaining from cloud functions.

Follow up to 2361

---

src/pages/Admin/EntranceExperience/EntranceExperience.tsx
src/pages/Admin/EntranceExperience/EntranceExperience.types.ts
src/pages/AdminAdvancedSettings/AdminAdvancedSettings.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1237

fixed AV3 World admin: Profile questions

---

functions/taxonomy.js

Fixes possible compatibility issues for older Node.js environments

Make taxonomy.js export using CJS, not ESM

---

scripts/lib/documents.ts
scripts/lib/types.ts
scripts/lib/utils.ts
scripts/simulation/seat.ts
scripts/simulator/default.config.json5.example
scripts/simulator/simulator.config.json5.example

Now simulator seats:
- on seats not previously occupied by simulator run
- on seats that do not overlap with video

Fix simulator to seat on proper seats

---

functions/venue.js
src/api/admin.ts
src/components/molecules/VenueRoomItem/VenueRoomItem.tsx

- New spaces have parent id
- Room urls are lowercasing the name of the venue and remove the spaces when multiple words exist
- Remove 'theme' from venue, it's not used anywhere

pass parentId to newly created spaces

---

src/scss/colors.scss
src/scss/constants.scss

Minor update of the color generation in `colors.scss` along with some `@debt` comments for future improvements

Update the color generation

---

src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/hooks/useSocialSignIn.ts
src/pages/Account/Login.scss
src/settings/index.ts

Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1246
SSO for Google/Facebook

Added Google/FB auth

---

src/api/admin.ts
src/components/atoms/PortalVisibility/PortalVisibility.scss
src/components/atoms/PortalVisibility/PortalVisibility.tsx
src/components/molecules/AdminInput/AdminInput.tsx
src/components/molecules/EditRoomForm/EditRoomForm.tsx
src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
src/components/molecules/SpaceEditFormNG/SpaceEditFormNG.tsx
src/pages/Admin/AdvancedSettings/AdvancedSettings.tsx
src/pages/Admin/Venue/Rooms/RoomsForm.tsx
src/pages/Admin/Venue/VenueDetailsForm.tsx
src/pages/Admin/Venue/VenueDetailsSubForm.tsx
src/scss/constants.scss
src/settings/portalSettings.ts

Rework of PortalVisibility component that handles changes through useForm utilities.
A sub-PR of:
- https://github.com/sparkletown/sparkle/pull/2449

Update of PortalVisibility component for moving advanced settings to start

---

src/components/organisms/WorldStartForm/WorldStartForm.tsx

Fixes the world slug validation to work only when creating a world and not when updating a world.
Unblocks the world update.

check world slug only on creation

---

src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
src/components/molecules/SpaceEditFormNG/SpaceEditFormNG.tsx
src/components/templates/ArtPiece/ArtPiece.tsx
src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
src/components/templates/ViewingWindow/ViewingWindow.tsx
src/pages/Admin/AdminVenuePreview.tsx
src/utils/embeddableUrl.ts

Resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1161
Removed additional url check for iframe space video autoplay feature

removed unnecessary url autoplay check

---

src/utils/object.ts

Stop infinite objectEntries() recursion due to value being DOM object

---

functions/scheduled.js

Changes the update time to 1 minute; Fixes the premature deletion of old users based on the most recent test session

Changes the update time to 1 minute; Fixes the premature deletion of old users

---

src/components/molecules/NavBar/NavBar.tsx
src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
src/hooks/useWorldById.ts
src/hooks/worlds/useWorldBySlug.ts
src/pages/WorldEditor/WorldEditorAdvancedPanel.tsx
src/pages/WorldEditor/WorldEditorEntrancePanel.tsx
src/pages/WorldEditor/WorldEditorStartPanel.tsx

Adds a new hook for world searching by `worldSlug`. 
This hook will be required for the new in venue url `/in/:worldSlug/:venueSlug`

introduce useWorldBySlug hook for world searching

---

src/components/atoms/ImageInput/ImageInput.scss
src/components/atoms/ImageInput/ImageInput.tsx
src/components/organisms/WorldStartForm/WorldStartForm.scss
src/components/organisms/WorldStartForm/WorldStartForm.tsx
src/pages/Admin/Details/Form/DetailsForm.scss
src/pages/Admin/Details/Form/DetailsForm.tsx

Fixes image upload bug at world

fix image upload

---

src/components/molecules/AdminSpaceCard/AdminSpaceCard.tsx
src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
src/pages/Admin/Admin.tsx
src/pages/SpaceEditor/SpaceEditor.tsx

Fixes the admin navigation buttons and the login/register forms.

fix login and admin navigation

---

src/components/atoms/ButtonNG/ButtonNG.scss
src/components/atoms/SortDropDown/SortDropDown.scss
src/components/atoms/SortDropDown/SortDropDown.tsx
src/components/atoms/SortDropDown/index.ts
src/components/molecules/AdminTitleBar/AdminTitleBar.scss
src/pages/Admin/Admin.tsx
src/pages/SpacesDashboard/SpacesDashboard.scss
src/pages/SpacesDashboard/SpacesDashboard.tsx
src/scss/constants.scss
src/utils/venue.ts

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1459
**Before**:
**After**:

Update the SpacesDashboard layout as per IA requirement

---

src/components/organisms/TimingEventModal/TimingEventModal.scss
src/components/organisms/TimingEventModal/TimingEventModal.tsx

Resolves https://github.com/sparkletown/internal-sparkle-issues/issues/1513
Note: the delete button placement is temporary and will be getting moved to the list component in the near future.
New visuals:

Change the layout of the experience modal

---

functions/src/utils/venue.js
functions/venue.js
src/api/admin.ts
src/components/organisms/AdminVenueView/components/Spaces/Spaces.tsx
src/components/organisms/SpaceTimingForm/SpaceTimingForm.tsx
src/pages/Admin/BackgroundSelect/BackgroundSelect.tsx
src/pages/Admin/Details/Form/DetailsForm.tsx
src/utils/venue.ts

This creates a single unique and non-changing way of finding a venue in the database.
This closes https://github.com/sparkletown/internal-sparkle-issues/issues/1522
This also removes some older functions as updating them to support world ID made little sense.

Add venue ID to venue functions in the backend

---

src/components/molecules/AdminSpaceCard/AdminSpaceCard.tsx
src/components/organisms/AdminVenueView/AdminVenueView.tsx
src/components/organisms/AdminVenueView/components/EventCard/EventCard.tsx
src/components/organisms/AppRouter/AdminV3Subrouter.tsx
src/pages/SpacesDashboard/SpacesDashboard.tsx
src/settings/urlSettings.ts
src/utils/url.ts

Changes the url for space configuration to `admin/w/worldSlug/s/spaceSlug`
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1500

update space configuration url and route

---

src/components/atoms/SortDropDown/SortDropDown.scss
src/components/molecules/AdminTitleBar/AdminTitleBar.scss
src/components/molecules/AdminTitleBar/AdminTitleBar.tsx
src/components/organisms/AdminVenueView/AdminVenueView.scss
src/components/organisms/AdminVenueView/AdminVenueView.tsx
src/pages/SpacesDashboard/SpacesDashboard.scss
src/pages/SpacesDashboard/SpacesDashboard.tsx
src/scss/constants.scss

Sub-PR of 
- https://github.com/sparkletown/sparkle/pull/2607

AdminVenueView title bar without injected class name

---

.github/workflows/update-env-branches.yml

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1526

Update envs with admin v3

---

src/components/molecules/NavBar/NavBar.tsx
src/components/organisms/WithNavigationBar/WithNavigationBar.scss
src/components/organisms/WithNavigationBar/WithNavigationBar.tsx
src/pages/SpacesDashboard/SpacesDashboard.tsx
src/pages/VenuePage/TemplateWrapper.tsx
src/pages/VenuePage/VenuePage.tsx
src/pages/WorldEditor/WorldEditor.tsx
src/pages/WorldsDashboard/WorldsDashboard.scss
src/pages/WorldsDashboard/WorldsDashboard.tsx

Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1490
Redone `Create your first world` page. The world list page remains intact
Before:
After:

Create first world page redone

---

src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
src/forms/createPortalSchema.ts
src/forms/externalSpaceEditSchema.ts
src/forms/factory/createUrlSchema.ts
src/forms/roomSchema.ts
src/forms/spaceEditSchema.ts
src/pages/Admin/Venue/Rooms/RoomsValidationSchema.ts

Fixes non-external portal update scheme
Reference: https://doesitsparkle.slack.com/archives/C02DPU9KF1A/p1638364391412200

fixed non-external portal settings update

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx

Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1504

[master-v1] Fixes wrong room redirect in schedule

---

src/components/molecules/WorldCard/WorldCard.tsx
src/pages/WorldsDashboard/WorldsDashboard.scss
src/pages/WorldsDashboard/WorldsDashboard.tsx

Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1489
Before:
After:

world list page redone

---

src/pages/WorldsDashboard/WorldsDashboard.scss
src/pages/WorldsDashboard/WorldsDashboard.tsx

Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1538
Styles fix

styles fix for new world page

---

src/components/organisms/NewProfileModal/components/header/ProfileModalBasicTextInfo/ProfileModalBasicTextInfo.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1542

Remove 'last seen in' from Profile Modal

---

src/components/molecules/WorldNav/WorldNav.tsx
src/settings/urlSettings.ts

Recent routing changes have broken editing worlds. This fixes it.

Fix URLs for editing worlds

---

src/components/organisms/AdminVenueView/components/EventsView/EventsView.tsx
src/components/organisms/TimingEventModal/TimingEventModal.tsx
src/components/organisms/TimingSpace/TimingSpace.tsx

This also fixes the "create experience" button in this view
Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1581

Fix splitting of events by space

---

src/components/templates/ExternalRoom/ExternalRoom.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1407

Fix external experience default icon

---

src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx

Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1477 by reimplementing the reconnect function

[staging-av1] Fixes videos not showing up on retry

---

src/components/atoms/SpacesDropdown/SpacesDropdown.tsx
src/components/organisms/PortalAddEditForm/PortalAddEditForm.tsx

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1596
- https://github.com/sparkletown/internal-sparkle-issues/issues/1585

Show all spaces alphabetised in portal modal

---

src/components/atoms/ChatMessage/ChatMessage.tsx

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1582
Bit dirty, but, removes the threaded reply option in a minimal way.

Disable threaded replying to DMs

---

src/components/organisms/AdminVenueView/components/PrettyLink/PrettyLink.scss
src/components/organisms/PortalStripForm/PortalStripForm.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1580
BEFORE
AFTER

Fix portal table-cell width in the admin panel

---

src/components/organisms/PortalStripForm/PortalStripForm.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1578

Fix tabindex of the toggle containers in the portals list

---

src/components/molecules/TablesUserList/TablesUserList.tsx
src/components/organisms/Room/VideoErrorModal.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1589
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1476

Changes modal text. Makes modal non-dissmissable

---

src/components/molecules/ReactionsBar/ReactionsBar.scss
src/components/molecules/ReactionsBar/ReactionsBar.tsx
src/components/templates/Auditorium/components/Section/Section.tsx
src/components/templates/Jazzbar/JazzBar/JazzBar.tsx

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1599
This is code that I have lifted from 6.sparkle.space with minimal modification. In the long run we should turn this into a proper component.

Reintroduce shoutouts

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx

This was causing bugs in what URL was being copied
Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1597

Remove use of room from schedules

---

src/components/molecules/TablesUserList/TablesUserList.tsx
src/components/organisms/Room/VideoErrorModal.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1590

Fixes text and bug in Music venue

---

src/components/molecules/ProfilePictureInput/ProfilePictureInput.scss
src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx

Adds border radius to the profile picture when registering.
Introduced in: https://github.com/sparkletown/sparkle/commit/92d25e31dde11d663038065cd63934c1b5ebb0ea
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1515

add border radius to profile picture

---

src/components/molecules/Schedule/Schedule.tsx

fixed event start time prop use

---

src/components/molecules/Schedule/Schedule.tsx

Co-authored-by: Oleksii Petrov <oleksii.petrov@altexsoft.com>

fixed event start time prop use (#2705)

---

src/pages/VenuePage/VenuePage.tsx
src/types/User.ts
src/utils/profile.ts
src/utils/user.ts

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1620

Record the worlds that a user has visited and use to determine showing world entrance

---

functions/world.js
src/api/world.ts

* fixed entrance/user questions delete
* remove console
Co-authored-by: Oleksii Petrov <oleksii.petrov@altexsoft.com>

fix entrance step delete (#2712)

---

src/components/organisms/AdminVenueView/components/Spaces/Spaces.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1569

Hide 'Create Portal' button for non-map spaces

---

src/hooks/useVenueScheduleEvents.ts
src/utils/event.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1625

Fix days difference counting in the schedule

---

src/components/organisms/AppRouter/AppRouter.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1631

Adds Honeycomb hacky redirect

---

src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
src/utils/event.ts

fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1625

[AV1] Fix fix schedule days

---

src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
src/utils/event.ts

Deploy staging-av1 -> master-av1

---

src/components/molecules/ScheduleItemNG/ScheduleItemNG.scss
src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1607

[admin v1] Removes copy event link button

---

src/components/organisms/AppRouter/AppRouter.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1631

Fixes temp Honeycomb slug

---

functions/index.js
functions/venue.js

Follow up for https://github.com/sparkletown/sparkle/pull/2735
* Removed `??` from the venue.js and replaced with `||`

remove stats exports + replace ?? for firebase function

---

craco.config.js
package-lock.json
package.json

This should enable source maps when building for any of our environments.

Upload source maps to bugsnag on build

---

src/components/molecules/UserList/UserList.tsx

Remove '0' from the portal attendees list

---

.circleci/config.yml
src/api/admin.ts
src/api/world.ts
src/hooks/spaces/useSpaceParams.ts

Reference: https://doesitsparkle.slack.com/archives/C02T8927HL7/p1642434434023600
Added an extra step with:
* Upgraded node version to 16.13 @ Circle CI
* Ensure latest NPM is installed

Upgrade node version at circle ci

---

functions/venue.js
src/api/admin.ts
src/components/molecules/PortalsTable/PortalsTable.tsx
src/components/molecules/ScreeningRoomVideoAddEditModal/ScreeningRoomVideoAddEditModal.tsx
src/components/molecules/ScreeningRoomVideoAddEditModal/index.ts
src/components/molecules/ScreeningRoomVideosTable/ScreeningRoomVideosTable.scss
src/components/molecules/ScreeningRoomVideosTable/ScreeningRoomVideosTable.tsx
src/components/molecules/ScreeningRoomVideosTable/index.ts
src/components/organisms/AdminVenueView/components/Spaces/Spaces.tsx
src/components/organisms/ScreeningRoomVideoAddEditForm/ScreeningRoomVideoAddEditForm.scss
src/components/organisms/ScreeningRoomVideoAddEditForm/ScreeningRoomVideoAddEditForm.tsx
src/components/organisms/ScreeningRoomVideoAddEditForm/index.ts
src/components/organisms/ScreeningRoomVideosStripForm/ScreeningRoomVideosStripForm.scss
src/components/organisms/ScreeningRoomVideosStripForm/ScreeningRoomVideosStripForm.tsx
src/components/organisms/ScreeningRoomVideosStripForm/index.ts
src/forms/screeningRoomVideoSchema.ts
src/pages/Admin/ScreeningRoomPreview/ScreeningRoomPreview.scss
src/pages/Admin/ScreeningRoomPreview/ScreeningRoomPreview.tsx
src/pages/Admin/ScreeningRoomPreview/index.ts
src/settings/spacePortalsSettings.ts
src/utils/file.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1654
screenshots of the screens:
Add/edit modal

Admin panel for Screening room

---

docs/load-results.md

Adds all data related to load testing of the platform
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1639

Sums up the loading experience

---

firestore.rules

Fixes firestore rules to properly deploy

Fixes firestore rules to properly deploy

---

src/components/organisms/AdminVenueView/components/RunTabUsers/RunTabUsers.tsx
src/components/organisms/AdminVenueView/components/RunTabView/RunTabView.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1721

Fix visibility of the RunTabUsers component

---

src/hooks/twilio/useVideoRoomState.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1719

Fixes user video in Poster page

---

src/components/templates/PosterPage/usePosterVideo.ts

finally fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1719

Fixes poster video

---

firestore.rules
scripts/upload-poster-hall.ts
src/utils/image.ts

Fix bugs found while Outlier event was going on

---

functions/src/analytics.ts
functions/src/utils/permissions.ts
functions/src/world.ts

fixes not working tools script

Adds missing function in analytics

---

.circleci/config.yml

Fixes broken function deploy checker

Fixes broken function deploy checker

---

package-lock.json
package.json
src/components/atoms/VenueWithOverlay/VenueWithOverlay.tsx
src/components/attendee/VideoHuddle/VideoHuddle.tsx
src/components/molecules/SubmitError/SubmitError.tsx
src/components/molecules/TableComponent/TableComponent.tsx
src/components/molecules/TablesUserList/TablesUserList.tsx
src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
src/components/templates/Jazzbar/components/JazzBarRoom/JazzBarRoom.tsx
src/pages/VenueLandingPage/VenueLandingPageContent.tsx

Two files with added "ignore unused variables" directives that should be removed later on:
- `src/components/templates/Jazzbar/JazzBar/JazzBar.tsx`
- `src/components/attendee/VideoHuddle/VideoHuddle.tsx`

Ran npm run reformat

---

src/components/atoms/ButtonNG/ButtonNG.tsx
src/components/atoms/Checkbox/Checkbox.tsx
src/components/atoms/Dropdown/Dropdown.scss
src/components/atoms/Dropdown/Dropdown.tsx
src/components/atoms/UserStatusDropdown/UserStatusDropdown.scss
src/components/molecules/Chatbox/components/ChatboxOptionsControls/ChatboxOptionsControls.scss
src/components/molecules/Chatbox/components/ChatboxOptionsControls/ChatboxOptionsControls.tsx
src/components/organisms/BannerAdmin/BannerAdmin.tsx
src/components/templates/PartyMap/components/PortalModal/PortalModalContent.tsx
src/scss/constants.scss

Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1723
Partially resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1692
|**BEFORE** | **AFTER**|
|-------------|-----------|
|![sparkle-chat-options-02](https://user-images.githubusercontent.com/79229621/152965407-622c910e-dab3-43ee-9899-1cd9cc3dc200.png)|![sparkle-chat-options-01](https://user-images.githubusercontent.com/79229621/152965443-70b2372a-a06e-40a4-8568-40da995a8a8d.png)|

Rework some of Dropdown styles to make chat options work

---

functions/src/analytics.ts

Fixes wrong field name

---

functions/src/analytics.ts
functions/src/index.ts
functions/src/user.ts
functions/src/utils/venue.ts
functions/src/utils/world.ts
functions/src/venue.ts
src/pages/Admin/ToolsPage/ToolsPage.tsx
src/pages/Admin/ToolsPage/components/Tool/Tool.tsx
src/pages/Admin/ToolsPage/scripts/analytics/config.ts
src/pages/Admin/ToolsPage/scripts/analytics/index.ts
src/pages/Admin/ToolsPage/scripts/index.ts
src/pages/Admin/ToolsPage/scripts/makeWorldOwner/AddWorldOwnerOutput.scss
src/pages/Admin/ToolsPage/scripts/makeWorldOwner/AddWorldOwnerOutput.tsx
src/pages/Admin/ToolsPage/scripts/makeWorldOwner/config.ts
src/pages/Admin/ToolsPage/scripts/makeWorldOwner/index.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1657

Implements world admins addition functionality

---

.github/workflows/update-env-branches.yml

Disables sparkle 2 deployment
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1730

Disables sparkle 2 deployment

---

.circleci/config.yml

Configures CircleCi to deploy redesign-2021 branch to sparkle-7

Deploy redesign-2021 branch to sparkle-7

---

src/components/admin/LinkButton/LinkButton.tailwind.ts
src/components/admin/LinkButton/LinkButton.tsx
src/components/admin/LinkButton/index.ts
src/components/admin/SpaceCard.tsx
src/pages/SpacesDashboard/SpacesDashboard.tsx

Use the correct create-space URL
Fix width of the Edit buttons

Fix bugs on the Spaces page

---

src/components/attendee/Header/AttendeeHeader.tsx
src/components/attendee/NavOverlay/NavOverlay.tsx
src/components/attendee/NavOverlay/ScheduleOverlay/ScheduleOverlay.tsx

Fix for `redesign-2021` https://app.circleci.com/pipelines/github/sparkletown/sparkle/14104/workflows/675a65dd-a780-4ecd-8cdc-3c9061bd1045/jobs/21168

fix redesign-2021 build error

---

src/components/attendee/Attendance/Attendance.module.scss
src/components/attendee/AttendeeLayout.module.scss
src/components/attendee/ChatContainer.module.scss
src/components/attendee/VideoHuddle/VideoHuddle.module.scss

Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1743
- https://github.com/sparkletown/internal-sparkle-issues/issues/1742

Minor layout fixes

---

src/components/templates/Auditorium/Auditorium.tsx
src/components/templates/Auditorium/components/AllSectionPreviews/AllSectionPreviews.tsx
src/components/templates/Auditorium/components/SeatingBlock/SeatingBlock.tsx
src/components/templates/Auditorium/components/SeatingBlock/index.ts
src/components/templates/Auditorium/components/Section/Section.module.scss
src/components/templates/Auditorium/components/Section/Section.tsx
src/hooks/auditorium/seats.module.scss
src/hooks/auditorium/useAllAuditoriumSections.ts
src/hooks/auditorium/useAuditoriumGrid.tsx
src/hooks/auditorium/useAuditoriumSection.ts
src/scss/attendee/theme.scss
src/settings/index.ts
src/utils/auditorium.ts

Sections are not implemented - that UI can come later.

Auditorium

---

src/components/admin/EventsPanel/EventsPanel.tsx
src/components/atoms/Dropdown/Dropdown.tsx
src/pages/Admin/WorldSchedule/WorldSchedule.tsx

Minor fixes and tweaks for the world schedule and the dropdown color. Also wraps the page with `<AdminRestricted/>` to prevent normal users from accessing the page.

tweaks for world schedule and it's components

---

functions/analytics.js
src/pages/Admin/ToolsPage/scripts/analytics/AnalyticsOutput.tsx
src/pages/Admin/ToolsPage/scripts/analytics/config.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1641

Fixes analytics for WayFair

---

src/components/atoms/InputField/InputField.tsx
src/components/atoms/UserAvatar/UserAvatar.module.scss
src/components/atoms/UserAvatar/UserAvatar.tsx

Chat user avatar size fix
Ref: 
- https://doesitsparkle.slack.com/archives/C02DPU9KF1A/p1646816581213919
Before:
After:

fix chat avatar style

---

src/components/attendee/TableComponent/TableComponent.module.scss
src/components/attendee/TableComponent/TableComponent.tsx
src/components/attendee/TableGrid/TableGrid.tsx
src/components/molecules/SpaceInfo/SpaceInfo.module.scss
src/components/molecules/SpaceInfo/SpaceInfo.tsx
src/components/molecules/SpaceInfo/index.ts
src/components/molecules/StartTable/StartTable.tsx
src/components/templates/ConversationSpace/ConversationSpace.hoc.tsx
src/components/templates/ConversationSpace/ConversationSpace.tsx
src/components/templates/ConversationSpace/index.ts
src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
src/components/templates/Jazzbar/JazzBarPage.tsx
src/pages/VenuePage/TemplateWrapper.tsx
src/types/Table.ts

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1725

Redesign: Conversation Space

---

src/components/attendee/TableGrid/TableGrid.tsx

Fix TableGrid component

---

src/components/templates/ExternalRoom/ExternalRoom.module.scss
src/components/templates/ExternalRoom/ExternalRoom.tsx
src/pages/VenuePage/TemplateWrapper.module.scss

closes https://github.com/sparkletown/internal-sparkle-issues/issues/1712
designs at: https://www.figma.com/file/DltmqgBfdkgyX7z5Uv4r15/HiFi%3A-Visual-Redesign---Shared-w-Eng?node-id=1111%3A3431

Adds new external room

---

src/components/molecules/Chatbox/Chatbox.module.scss
src/components/molecules/Chatbox/Chatbox.tsx

closes https://github.com/sparkletown/internal-sparkle-issues/issues/176
https://user-images.githubusercontent.com/63194656/158488722-c0434e3e-0070-481b-87a5-a27abee5f8aa.mov

Makes chatbox display the latest messages

---

src/components/atoms/LinkButton/LinkButton.tsx
src/components/molecules/AnnouncementMessage/AnnouncementMessage.tsx
src/utils/url.ts

Ref: https://doesitsparkle.slack.com/archives/C01H9D1P1PE/p1647626388615959
Force funnel banner links will now reload the page

Force funnel link to reload page
