- src/components/organisms/RadioModal/RadioModal.tsx
Replaces the title and the description of the Radio popup with the ones provided in ticket 216 from trello.
> tweak radio title and description

- src/components/templates/Camp/components/RoomList.tsx
- src/components/templates/Camp/components/RoomModal.tsx
On the Camp page- this no longer has any function in this context, so complete removal (via commenting out)
Remove the whole message at the bottom "what's on now/ loading" (you can comment it out.
> Remove of Camp page message at the bottom "what's on now/ loading" 

- src/components/molecules/Message/Message.tsx
- src/components/organisms/ChatDrawer/ChatDrawer.scss
- src/scss/global.scss
Fixes for the playa and venue chat - https://trello.com/c/M4QW5YVS
1. Show author and time of the message above the bubble next to profile pic
2. Long bubble text are displayed on multiple lines, and shared URL are broken to not bust out of the container
3. Restyled chat scrolling bar
> Fixes for the playa and venue chat

- src/components/molecules/NavBar/NavBar.tsx
- src/components/organisms/RadioModal/RadioModal.tsx
- src/hooks/useRadio.ts
https://trello.com/c/a5wZE7Y9 
1. Radio popup now opens only on first Playa visit,
2. Radio audio now starts to play upon visit the Playa with 10% volume (for the first time visitor)
3. Radio audio now resume upon subsequent visit the Playa with X% volume where X = last value set by the visitor
> Shouting Fire Radio fixes

- src/components/templates/Playa/AvatarLayer.tsx
The useEffect hook cleanup was destroying the websocket and recreating once per venue, no doubt overloading the websocket relay backend.
> Reduce number of inits of the websocket to 1

- src/components/templates/Playa/PlayaBackground.tsx
Fix wrong hours range for Playa Background color logic - https://trello.com/c/USgXbKW7
> Fix wrong hours range for Playa Background color logic

- src/components/templates/Camp/components/Map.scss
- src/components/templates/Camp/components/Map.tsx
- src/components/templates/Camp/components/RoomModalOngoingEvent.tsx
https://trello.com/c/QoSq0lTJ/8-make-basic-party-map-modals-become-the-full-black-popup-as-before
Fix to make a onClick from map to show the same modal as room-list, whilst keeping IS_BURN logic the same.
> Fix/revert basic party modal 

- src/pages/VenuePage/VenuePage.tsx
- src/types/Venue.ts
- src/utils/useLocationUpdateEffect.ts
- Remove updateLocationData from the hook because it was running on every tab
- Conditionally update the location of the profile only when it's not available in the firebase
> add disable option to location update

- LICENSE.agpl
The Section 13 provision of AGPL closes a loophole that would have allowed anyone to take the software and run it on a server in a closed fashion without needing to provide source as they were not distributing it. AGPL has a specific provision that prevents this.
More detail here: https://opensource.stackexchange.com/questions/5041/of-the-differences-between-the-gplv3-and-the-agplv3-texts-what-to-make-of-them
> Relicense Sparkle to AGPL

- src/pages/Admin/AdminEventModal.tsx
The default value was empty string and that was always being send to the firebase, now its undefined and the component can trigger onChange correctly when the user is typing
> fix event creation in admin

- src/components/molecules/PrivateRecipientSearchInput/PrivateRecipientSearchInput.scss
The hover color "$primary" was yellow and the text was white which was hard to read. Now it's $dark + darken because the background itself is $dark
> change chat hover color to make text visible

- src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
- src/pages/Account/CodeOfConduct.tsx
- src/pages/Account/Profile.tsx
- src/pages/VenueLandingPage/VenueLandingPage.tsx
- Move returnUrl logic one step deeper to avoid the direct back to the first step
- Make join event button redirect directly to /in/ instead of entrance page
- Add account profile page to the registration flow because it was missing in some of the cases
> fix redirect after account creation

- functions/venue.js
(Ref: https://trello.com/c/7MzYxfQE)
When updating venues other than theme camps (eg. Music Venue), `showGrid` isn't a toggle shown on the frontend, so there was no data being sent through for it, resulting in `undefined`.
The backend `updateVenue` function wasn't checking `showGrid`/`showLiveSchedule` values before adding them to the `updated` data.
This led to a backend error within firestore, which eventually resulted in cryptic error `One or more errors occurred when saving the form:` being shown to the user on the frontend, and the following error in the DevTools console:
```
Error: INTERNAL
at new t (error.ts:66)
at error.ts:175
at e.<anonymous> (service.ts:231)
at tslib.es6.js:100
at Object.next (tslib.es6.js:81)
at a (tslib.es6.js:71)
```
> Fix backend function updateVenue to properly check showGrid/showLiveSchedule

- src/components/templates/Camp/components/Map.tsx
There is css which adds padding to the first child of the grid and when the grid is missing this breaks the first room UI in the array. This fixes the issue by conditionally rendering a div when the grid is missing.
> fix first child ui bug when grid is missing

- .github/mention-to-slack.yml
- .github/workflows/mention-to-slack.yml
This forks https://github.com/marketplace/actions/github-mention-to-slack in case it is ever compromised and so we can control the feature set, and makes it available in Sparkle repo as a GH action.
> GitHub mention bot via GH Action

- src/hooks/useCampPartygoers.ts
([ref](https://trello.com/c/KdLgkkbe))
**Note:** this PR is opened directly against `master` as this fix is urgent, and staging is currently not in an available state.
This bug is occasionally showing a black screen when logging in and/or when logging in for the first time, which is blocking upcoming events.
The types say that this shouldn't be possible, but the types are clearly wrong:
- https://github.com/sparkletown/sparkle/blob/staging/src/types/Firestore.ts#L73-L95
I believe technically all of these keys could be undefined, so they should really be `?` for all of them.
> [MASTER][BUGFIX] fix undefined TypeError in useCampPartygoers hook

- src/pages/Admin/Venue/TemplateForm.tsx
When the images were `undefined` it would show broken links, now it just won't try and show an image there. 💅
> fix Admin Venue TemplateForm component to not show broken images

- src/components/templates/Camp/components/Map.tsx
- src/components/templates/PartyMap/components/Map/Map.tsx
- src/pages/Admin/Admin.tsx
Partygoers seem to be duplicated sometimes, but the duplicates don't have id's.
> workaround bouncy partygoers without id + admin subvenue room fixes

- .circleci/config.yml
Since it's broken currently this shouldn't hurt anything, and will reduce the noise on our notifications (and our brains for having to mentally filter out the 'important' from the 'not important' notifications)
> Disable smoke-test in CircleCI config (as it is broken currently anyway)

- .circleci/config.yml
- src/index.tsx
This replaces the `basic_fail_1` template ([ref](https://github.com/CircleCI-Public/slack-orb/blob/master/src/message_templates/basic_fail_1.json)) with a custom template that makes the messages slimmer and less spammy.
> Add custom 'slim' template to circleci slack/notify on fail step

- src/components/organisms/ChatDrawer/ChatDrawer.scss
- src/components/templates/Camp/components/Map.scss
increases the z-index of info drawer and chat because some of the elements in camp now have z-index 1
> fix z-index of drawers

- src/components/templates/Camp/components/CampAttendance.tsx
- src/components/templates/Camp/components/MapRoomOverlay.tsx
- src/components/templates/PartyMap/components/RoomAttendance.tsx
This PR **should** hide the tiny blue circle when hovering an empty room, on both the partymap and themecamp templates.
> Hide attendance boxes when there are zero attendees

- src/components/molecules/EventDisplay/EventDisplay.tsx
- src/components/molecules/LiveSchedule/LiveEvent.tsx
- src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
TypeScript did not catch that Record<> can return undefined if the key is not present. This appears to be a deficiency in the Record<> type. More info here: https://fnune.com/typescript/2019/01/30/typescript-series-1-record-is-usually-not-the-best-choice/
This fix wraps the cast in a Partial<> to force handling of the undefined case. Fortunately, no other areas were affeted by this specific bug.
> Fix crash in events

- src/components/molecules/UserList/UserList.tsx
- src/components/templates/Camp/components/CampAttendance.tsx
- src/components/templates/Camp/components/Map.scss
- src/components/templates/Camp/components/RoomModalOngoingEvent.tsx
- src/components/templates/PartyMap/components/RoomModalOngoingEvent/RoomModalOngoingEvent.tsx
- src/hooks/useCampPartygoers.ts
- fixes camp room counting display which was in column instead of row. now number of room attendance is next to the icon
- useCampPartygoers now checks for online users which were in the camp between the last update and now, instead of just now.
- remove mutation of prop
- replace anchors with buttons to disable new tab opening with wheel click and right click
> tweak room counting and uncounting

- src/components/molecules/Sidebar/Sidebar.tsx
Fixes `TypeError: Cannot assign to read only property '0' of object '[object Array]'` in the `SideBar` component due to trying to `.sort()` the array before the `.slice()` (which appears to have been introduced in https://github.com/sparkletown/sparkle/pull/830)
Ref: https://stackoverflow.com/questions/53420055/error-while-sorting-array-of-objects-cannot-assign-to-read-only-property-2-of/53420326#53420326
> Fix TypeError: Cannot assign to read only property '0' of object '[object Array]' in SideBar component

- package-lock.json
- package.json
Ref: https://github.com/browserslist/browserslist#browsers-data-updating
> You need to do it regularly for two reasons:
> 
> 1. To use the latest browser’s versions and statistics in queries like `last 2 versions` or `>1%`. For example, if you created your project 2 years ago and did not update your dependencies, `last 1 version` will return 2 year old browsers.
> 2. `caniuse-lite` deduplication: to synchronize version in different tools.
> Add browserslist:update-db helper script + update the underlying caniuse-lite dependency

- src/index.tsx
> Stub out BugsnagErrorBoundary with React.Fragment when we're not using Bugsnag

- .codeclimate.yml
Adds Code Climate configuration file to the repo as per:
- https://docs.codeclimate.com/docs/advanced-configuration
Note: the settings as configured here are pretty much the defaults, but mapped out explicitly. We can customize it more in a future PR if we want to.
> Create Code Climate config file

- src/utils/url.ts
This check seems to be failing for some zoom links for some reason. While we debug/figure that out, we'll allow links to be opened as per the old logic without this check.
> Disable utils/url isValidUrl check in openUrl

- src/components/templates/Audience/Audience.scss
- src/components/templates/Audience/Audience.tsx
Not sure if this is the fix we want. Instead of enlarging the video and make it hide the top seats, now it shrinks from the sides (width only) and doesn't collide with the seats.
> shrink video when audience aspect ratio is 16:9

- src/components/templates/ConversationSpace/ConversationSpace.tsx
- src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
The video room names were the same and people were getting in different tables and venues but the same video rooms because the table reference was the same
> make video room names unique

- package-lock.json
- package.json
Doesn't seem like there should be any breaking issues, may fix some bugs. Clicked through a little locally and it seemed to work. Would be good to give it a little more robust testing in staging.
- https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md
> upgrade twilio video to 2.9.0

- package.json
Run _ESLint_ only on JavaScript related files
This is due to the script failing while trying to lint _.scss_ or _.css_ files and not allowing the commit to continue
> 🚧 lint only javascript related files

- package-lock.json
- package-lock.test.ts
- package.json
It seems that when https://github.com/sparkletown/sparkle/pull/872 was merged it caused errors while trying to deploy the hosting, due to a TypeScript compilation error:
- https://app.circleci.com/pipelines/github/sparkletown/sparkle/3822/workflows/5974d56e-9d2c-41c1-a041-f4523b99e947/jobs/6370
```
TypeScript error in /home/circleci/project/src/components/molecules/AnnouncementMessage/AnnouncementMessage.tsx(33,30):
Type 'IconDefinition' is not assignable to type 'IconProp'.
Type 'IconDefinition' is not assignable to type 'IconLookup'.  TS2322
```
I believe the versions of the fontawesome libs need to be kept in sync with one another, this PR will fix that.
I'd also like to understand the differences in the `package-lock.json` (i expect there will be multiple versions of a common …
> fix fontawesome issues introduced in recent version bump 

- src/components/templates/PartyMap/components/Map/Map.scss
Safari doesn't seem to use width to set height the way Chrome does:
https://stackoverflow.com/questions/11276367/forcing-aspect-ratio-with-css-doesnt-work-on-safari
This fix explicitly sets the height on the map background image, so it doesn't default to the intrinsic height of the image.
> Fix partymap height for safari

- src/pages/VenuePage/VenuePage.tsx
useEffect hook for mixpanel was causing an error because the `venue.template` was undefined.
> Prevent mixpanel failing if no venue template is passed

- .firebaserc
- firebase.json
Follow on to https://github.com/sparkletown/sparkle/pull/990 to fix a typo I made (had to use `sparkle-2a` when creating the firebase project as `sparkle-2` was already taken)
> fix sparkle-2 environment config

- .circleci/config.yml
Follow on to https://github.com/sparkletown/sparkle/pull/990 and https://github.com/sparkletown/sparkle/pull/994 to fix a typo I made (had to use `sparkle-2a` when creating the firebase project as `sparkle-2` was already taken)
> fix sparkle-2 environment config (round 2)

- .firebaserc
Follow on to https://github.com/sparkletown/sparkle/pull/990, https://github.com/sparkletown/sparkle/pull/994, and https://github.com/sparkletown/sparkle/pull/995 to fix a typo I made (had to use `sparkle-2a` when creating the firebase project as `sparkle-2` was already taken)
> fix sparkle-2 environment config (round 3)

- .circleci/config.yml
- .firebaserc
- firebase.json
- src/index.tsx
This should be the required configuration changes for setting up/deploying the `sparkle-3` through `sparkle-10` environments.
Based on reviewing the code changes made in https://github.com/sparkletown/sparkle/pull/984 + the 'direct to branch' commits made following (which are collected together in https://github.com/sparkletown/sparkle/pull/989), and following the same model as https://github.com/sparkletown/sparkle/pull/990
> add configuration for sparkle-3 to sparkle-10 environments

- functions/index.js
Hopefully this will help shed some light on errors such as https://app.circleci.com/pipelines/github/sparkletown/sparkle/3953/workflows/b5eae2dd-a1e7-451d-a3e5-9ab4a1375853/jobs/6603
```
Error: Error occurred while parsing your function triggers.
TypeError: Cannot read property 'id' of undefined
at Object.<anonymous> (/home/circleci/project/functions/index.js:8:40)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Module.require (internal/modules/cjs/loader.js:1036:19)
at require (internal/modules/cjs/helpers.js:72:18)
at /home/circleci/project/functions/node_modules/firebase-tools/lib/ …
```
> be more explicit with errors + show functions.config()

- scripts/clone-events-across-firebase-projects.ts
Similar in function to https://github.com/sparkletown/sparkle/pull/987, this script allows us to clone the event data for the specified venue(s) from one firebase project (eg. production) to another (eg. staging)
Note: it will also save a local backup of the destination venue events before overwriting them.
> add scripts/clone-events-across-firebase-projects

- src/settings.ts
Fixes editing of rooms on partymap template venues. There is currently no admin tool to change a template for a venue, so we should not break the partymap venues
> Re-add support for themecamp template to admin tools

- src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
- src/types/VenueEvent.ts
Removed `Math.random()` from `key=` assignment.
This was a possible cause to events being duplicated in the UI
> Event duplication

- src/components/molecules/VenueChat/VenueChat.tsx
- src/components/organisms/Chatbox/Chatbox.tsx
- src/hooks/useConnectVenueChats.ts
This fix brings back the `useFirestoreConnect` in `ChatContext` which was filling out the `venueChats`. It was not brought across in #956 nor in #1007, but is referenced in the code.
> Restore venueChats after removal of contexts

- src/index.tsx
Both these settings affect whether duplicate listeners can be attached to a given path.
This affects the behavior of this function: https://github.com/prescottprue/redux-firestore/blob/master/src/actions/firestore.js
With this change, one heavier venue becomes responsive in 15 seconds vs. 60 seconds without.
We should test whether some other data goes missing with this change present.
> Prevent multiple listeners

- src/components/molecules/ChatsList/ChatsList.tsx
- src/components/organisms/Chatbox/Chatbox.tsx
- src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
- src/hooks/roles.ts
- src/hooks/useConnectRelatedVenues.ts
- src/hooks/useFirestoreConnect.ts
- src/hooks/useVenueId.ts
- src/hooks/users.ts
- src/pages/Admin/Admin.tsx
- src/pages/ReactionPage/ReactionPage.tsx
- src/pages/SparkleSpaceMarketingPage/WelcomePage/WelcomePage.tsx
- src/pages/VenueLandingPage/VenueLandingPage.tsx
- src/pages/VenuePage/VenuePage.tsx
- src/types/Firestore.ts
Sub-PR to https://github.com/sparkletown/sparkle/pull/801 that constrains the `useFirestoreConnect` query types to enforce our firestore query patterns.
This reinstates and improves upon the original type narrowing intended by https://github.com/sparkletown/sparkle/pull/784, as called out in https://github.com/sparkletown/sparkle/pull/801#issuecomment-759752827
> [sub-PR] Constrain useFirestoreConnect query types to enforce our firestore query patterns

- README.md
Bugsnag's open source program requires the logo to be linked to their website, they requested a "backlink to Bugsnag". This change adds the link to the image.
> Make Bugsnag logo a link per open source program requirements

- src/components/organisms/AppRouter/AppRouter.jsx
- src/hooks/useVenueId.ts
- src/pages/Admin/Admin.tsx
- src/pages/Admin/AdminVenueRoomDetails.tsx
- src/pages/Admin/Venue/DetailsForm.tsx
- src/pages/Admin/Venue/Rooms/RoomsForm.tsx
- src/pages/Admin/Venue/VenueWizard.tsx
Some of the urls were missing in the `venuePaths` array which was being used to get the `venueId` in the hook. Because of this, the `venueId` was `undefined` when it wasn't. Also the url of the venue creation has been changed because there was a collision between: `/admin/venue/:venueId` and `/admin/venue/creation` 
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/194
> bug fixing for admin v1

- src/components/organisms/Chatbox/Chatbox.tsx
Fixes a bug introduced in https://github.com/sparkletown/sparkle/pull/1086 due to our CI seemingly not catching the linting error (possibly due to disabling branch protections to allow the sync merge)
> Fix missing import in Chatbox after syncing master -> staging

- src/hooks/useVenueId.ts
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/164
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/194
This should also fix an edge case bug that was missed in https://github.com/sparkletown/sparkle/pull/1083 that causes the 'map banner' to not be editable (gets stuck on an infinite loading screen)
> I think we could just use `useParams()` here instead of needing to loop through all of the `venuePath`s, so long as they use `:venueId` in their path
> 
> - https://reactrouter.com/web/api/Hooks/useparams
>   - > `useParams` returns an object of key/value pairs of URL parameters. Use it to access `match.params` of the current `<Route>`
> 
> _Originally posted by @0xdevalias in https://github.com/sparkletown/sparkle/pull/1076#discussion_r557069059_
> Refactor useVenueId to use useParams instead of brittle venuePaths hack

- src/components/molecules/Footer/Footer.tsx
Opens the privacy policy link in a new tab just like the rest of the links in the footer.
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/200
> open privacy policy link in new tab

- src/components/molecules/TableHeader/TableHeader.tsx
- src/components/molecules/TablesUserList/TablesUserList.tsx
- src/components/templates/ConversationSpace/ConversationSpace.tsx
- src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
- src/hooks/useExperiences.ts
- src/types/Firestore.ts
- src/utils/selectors.ts
`experiences` were `undefined` because `venue.name` was `undefined` and the query was failing. `venueToUse` now is being used and `experiences` are fetched correctly. Types are also changed because the structure is different.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/199
> fixes jazzbar table lock/unlock functionality

- src/components/molecules/Chatbox/Chatbox.scss
- src/components/templates/Audience/Audience.scss
- src/components/templates/Audience/AudienceRouter.tsx
- src/components/templates/AvatarGrid/Router.tsx
- src/components/templates/Camp/Router.tsx
- src/components/templates/Jazzbar/JazzbarRouter/JazzbarRouter.tsx
- src/components/templates/PartyMap/PartyMapRouter.tsx
- src/components/templates/Playa/Router.tsx
- src/hooks/useVenueId.ts
- src/scss/constants.scss
Fixes the z-index in the audience template, avatars are now showing up underneath the video.
Fixes the route paths, they were using `match.url` instead of `match.path`. Example:
If path is `venue/:venueId` and url is `venue/denismusic` then the url replaces the path, and the params object is empty because path now looks like this: `venue/denismusic` and the venueId param doesn't exist anymore. Which then means that `useVenueId` returns `undefined` which is missleading.  This is necessary change and made here on purpose because audience templates were not working because of this issue.
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/201
> fix audience avatars and route paths

- src/components/molecules/NavSearchBar/NavSearchBar.scss
- src/components/molecules/NavSearchBar/NavSearchBar.tsx
- src/scss/constants.scss
- Ensure we don't use `index` for React component's `key` property.
- Because it doesn't uniquely identify the individual result, it causes issues when the item changes (but still has the same array index), which causes update issues (in this case, user profile pictures were showing for the wrong user, as it wasn't updated when the person in that 'search result slot' changed)
- Sets a max-height on `.nav-search-results` + enable scrolling
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/209
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/210
> fix NavSearchBar search result key stability + allow vertical scrolling

- package-lock.json
- package.json
fixes https://github.com/sparkletown/sparkle/issues/850
---
> From https://github.com/sparkletown/sparkle/issues/850:
> 
> - > https://github.com/facebook/create-react-app/issues/10045#issuecomment-763506381: dart-sass is the default option in sass-loader. So what you need to do it's just install sass and it will work. Docs regarding it should be updated
>   - `9.0.0` (2020-07-02): https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#900-2020-07-02
>     - > prefer `sass` (`dart-sass`) by default, it is strongly recommended to migrate on `sass` (`dart-sass`)
>   - `7.2.0` (2019-08-08): https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#720-2019-08-08
>     - > support auto resolving `dart-sass`
> - …
> Replace deprecated node-sass dependency with dart-sass

- .github/dependabot.yml
- the `reporting/` folder wasn't being tracked by dependabot, now it is
- we renamed `sparkletown/tech-leads` to `sparkletown/engineering-leads`, but this config was still using the old group name
> add reporting dependencies to dependabot + fix reviewers

- scripts/get-badges.ts
When running this script it seems that there was a user that couldn't be looked up, resulting in not having an entry in `usersById`. Due to the TypeScript typing on this, it implied that there could never be an undefined value for any given `userId` (which is incorrect). This also surfaced an issue where we weren't properly handling errors thrown within promises.
Before fixing these bugs, the error output looked like:
```
(node:95053) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'email' of undefined
at /Users/devalias/dev/sparkle/sparkle/scripts/get-badges.ts:102:40
at Array.map (<anonymous>)
at /Users/devalias/dev/sparkle/sparkle/scripts/get-badges.ts:99:34
at step (/Users/devalias/dev/sparkle/sparkle/scripts/get-badges.ts:44:23)
at Object.next …
```
> fix scripts/get-badges typing to properly handle potentially missing users + exit on errors properly

- src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
- src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
The guards were checking if result exists and were preventing the logic from finishing. Result is missing when venue access is not set and this is expected. Token won't be set if the venue access is missing (open) because everyone can join the party/event. Password on the other hand is tricky and needs further discussion. Because when you are creating an account, you don't have an input field for venue password and this might be a problem. The UX is the following:
Create account -> /in/ -> No Access -> /v/ -> Type password
We should probably redirect people to /v/ instead of /in/ when `venue.access` exists.
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/338
> fix account creation when venue access is missing

- src/components/atoms/Legend/Legend.styles.ts
- src/components/molecules/Chatbox/Chatbox.scss
- src/components/molecules/ChatsList/ChatsList.scss
- src/components/molecules/LoadingPage/loading.scss
- src/components/molecules/NavSearchBar/NavSearchBar.scss
- src/components/molecules/PrivateRecipientSearchInput/PrivateRecipientSearchInput.scss
- src/components/molecules/Sidebar/Sidebar.scss
- src/components/molecules/UserProfilePicture/UserProfilePicture.scss
- src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
- src/components/molecules/UserSearchBar/UserSearchBar.scss
- src/components/organisms/ChatDrawer/ChatDrawer.scss
- src/components/organisms/Chatbox/Chatbox.scss
- src/components/organisms/DustStorm/DustStorm.scss
- src/components/templates/Audience/Audience.scss
- src/components/templates/Jazzbar/JazzTab/JazzTab.scss
- src/components/templates/PartyMap/components/Map/Map.scss
- src/pages/Account/Account.scss
- src/pages/Admin/Admin.scss
- src/pages/Admin/Room/Modal/RoomModal.styles.ts
- src/pages/VenuePage/VenuePage.scss
- src/scss/constants.scss
- src/scss/global.scss
The user avatar image was showing above the various 'sidebar-like' components. 
- refactored all scss `z-index` to use our `z()` helper (to centralise this logic, and reduce future layering issues)
- add `@debt` comments to `z-index` locations within `styled-components` (until we can 💥  all of the `styled-components` in favour of plain scss)
- update all of our 'sidebar-like' layers to use `z-index` `15`
- fixes https://github.com/sparkletown/internal-sparkle-issues/issues/339
> refactor scss z-index's to use z() helper + fix user avatar 'sidebar' layering issues

- src/components/molecules/NavBar/NavBar.scss
- src/components/molecules/NavBar/NavBar.tsx
- src/components/molecules/NavBar/playa.scss
- src/components/molecules/NavSearchBar/NavSearchBar.scss
- src/components/molecules/Sidebar/Sidebar.scss
- src/components/organisms/SchedulePageModal/SchedulePageModal.tsx
- src/scss/constants.scss
This is a regression based on the changes I made to fix the z-index layering for the avatars in sparkletown/sparkle#1164:
- When searching for people in the `NavBar`, the search results list is 'behind' the `Sidebar`, so you can't see your results
- fixes https://github.com/sparkletown/internal-sparkle-issues/issues/352
- When viewing the Live Schedule, it is shown 'behind' the `Sidebar`, so the details get cut off
- fixes https://github.com/sparkletown/internal-sparkle-issues/issues/357
- When viewing the Live Schedule, the user's avatar was incorrectly shown on a layer 'above' it
The fixes here are, generally speaking, to ensure that each element is on an appropriate `z-index` layer, and that they are in the correct 'stacking context'. It's also worth noting that a child component can …
> fix z-index layering issues with NavBar, LiveSchedule, and SideBar

- .circleci/config.yml
For PRs from forked repos, CircleCI slack integration fails to run as the environment secrets aren't available to it. This PR resolves that by skipping the notification when the secret isn't available.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/397
Further reading:
- https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute
- https://circleci.com/docs/2.0/configuration-reference/#run
- https://support.circleci.com/hc/en-us/articles/360015562253-Conditionally-end-a-running-job-gracefully
> fix error in CircleCI when SLACK_ACCESS_TOKEN missing

- src/utils/getLinkFromText.tsx
use `React.Fragment` instead of `span` in `getLinkFromText`, as previously it would create some really ugly HTML output that was hard to play around with when tweaking styling/etc in devtools.
> use React.Fragment instead of span in getLinkFromText

- functions/package-lock.json
- functions/package.json
It seems that `npm-force-resolutions' has a bug in the newly released `0.0.4` version, that broke our function deploys:
- https://github.com/rogeriochaves/npm-force-resolutions/issues/22
- https://app.circleci.com/pipelines/github/sparkletown/sparkle/4983/workflows/3c630071-ff39-437b-8da2-475072e9b1ee/jobs/8146
- https://app.circleci.com/pipelines/github/sparkletown/sparkle/4986/workflows/ee140806-607b-4060-b1ee-346c1084a557/jobs/8151
- https://app.circleci.com/pipelines/github/sparkletown/sparkle/4988/workflows/ac40b430-afb2-47e3-b3d4-3ab1036b62b4/jobs/8155
While we did have the `0.0.3` version pinned in our `package.json`, we were using `npx` without the `--no-install` flag, which will resolve/download/install/use things on it's own.
This PR adds the `--no-install` flag, and refactors …
> fix npm-force-resolutions version issues

- functions/package-lock.json
- functions/package.json
In https://github.com/sparkletown/sparkle/issues/1214 I attempted to fix an issue we ran into with a broken version of this dependency being pushed. Turns out my fix was broken (see quoted context below).
While there is a new/fixed version, it seems that the reason we added it in the first place (see https://github.com/sparkletown/sparkle/commit/30d036987de0e6ce2c2b4c98790a16c2877a098c, seemingly to force the version of `websocket-extensions` to fix a security issue) is probably irrelevant now, as it seems to be the latest version anyway:
- https://www.npmjs.com/package/websocket-extensions
So removing it just seems like the easiest/best solution all around.
---
> Seems this didn't do the trick :(
> 
> - https://app.circleci.com/pipelines/github/sparkletown/sparkle/5010/workflows/935b0672- …
> remove npm-force-resolutions from /functions as we don't need it anymore

- functions/venue.js
- src/api/admin.ts
- src/pages/Admin/Venue/DetailsForm.tsx
Passes the venueId from the params and uses it for venue update in admin v1. This is not a bug per-say but it was an edge case introduced by directly manipulating data in the database. The venue name was changed by someone and it was different than the venue id which was returning an error when trying to find the venue by it's name instead of ID. Which is a big no no and should never be done.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/495
> fix venue edit by venue id when name is changed

- src/components/templates/Audience/Audience.scss
- src/components/templates/Audience/Audience.tsx
The 'center' video in the Auditorium would 'break out' of its 'container' and overlap seats. It seems its position was set based on the viewport of the browser, rather than it's containing parent.
It also seemed that when there were more seats than would fit on screen at one time, we weren't able to scroll around them.
And to top it off, the 'carved out section' in the middle always felt way too big/space wasting for the size of the video that was normally embedded within it.
I fixed all of the above + cleaned up a few things along the way. Since it's now possible for the 'seats' to extend outside of the window (requiring scrolling), I also auto-focus the central video container when the component is first rendered, so that the user starts off seeing that, rather than the top-left corner …
> fix Auditorium video container to be properly centred + some related cleanup

- src/components/templates/Audience/Audience.scss
- src/components/templates/Audience/Audience.tsx
- src/scss/constants.scss
Follow on to https://github.com/sparkletown/sparkle/pull/1237 that cleans up a few more little bits and pieces.
@mike-lvov It seems this will allow the seats and everything to still be clickable, without us needing to use an explicit `z-index`/etc.
Related reading:
- https://css-tricks.com/almanac/properties/p/pointer-events/
- https://caniuse.com/pointer-events
- https://stackoverflow.com/questions/3680429/click-through-div-to-underlying-elements/26799885#26799885
> Minor tweaks to Auditorium styles + related cleanup

- src/components/templates/Audience/Audience.scss
The video was inheriting the `pointer-events: none;` from the parent styles and the video was unclickable because of it.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/556
> fix audience unclickable video controls

- src/components/templates/PartyMap/components/Map/MapRoom.scss
Unclickable rooms were added in https://github.com/sparkletown/sparkle/pull/1225, but it seems we missed an edgecase. When hovering over rooms, the `.maproom:hover` `z-index` was being applied.
Also cleaned up a duplicate style/etc.
> ensure unclickable rooms maintain their z-index onHover

- src/components/templates/PartyMap/components/Map/MapRoom.scss
Deploys:
- ensure unclickable rooms maintain their z-index onHover (#1256)
> Deploy staging -> master

- src/components/molecules/Chatbox/Chatbox.tsx
- src/components/molecules/IframeAdmin/IframeAdmin.tsx
- src/components/molecules/OnlineStats/OnlineStats.tsx
- src/components/molecules/UserSearchBar/UserSearchBarInput.tsx
- src/components/organisms/BannerAdmin/BannerAdmin.tsx
- src/components/organisms/ChatSidebar/components/PrivateChats/PrivateChats.tsx
- src/components/templates/Audience/Audience.tsx
- src/components/templates/Playa/Playa.tsx
- src/pages/Account/Profile.tsx
closes https://github.com/sparkletown/internal-sparkle-issues/issues/571
> When I send chat messages, I get the 'suggestions' that I would get when filling out a form for the second/third time, but there aren't many cases when I would want to send the same text message multiple times (and it looks ugly)
---
> I believe the fix for this will just be adding  to the text field:
> 
> - https://css-tricks.com/snippets/html/autocomplete-off/
> 
> And if we want to 'scope creep' this issue a little bit, it might be nice to think about/enumerate all of the other places within our codebase where we would also not want these suggestions, and proactively add it to those as well.
> 
> _Originally posted by @0xdevalias in https://github.com/sparkletown/internal-sparkle-issues/issues/571#issuecomment-79 …
> Disable autocomplete suggestions when writing a chat message, shoutout or other input

- functions/venue.js
- src/settings.ts
- src/types/venues.ts
When attempting to edit an `embeddable`/`firebarrel` venue, the backend `updateVenue` function wasn't correctly updating the `iframeUrl` value.
This was likely due to the disparate locations that needed to be updated in our backend functions when adding new functionality. I did a minimal cleanup refactor on some of this to reduce the likelihood of this sort of issue occurring in future; + added some extra related comments/debt comments/etc.
As a workaround, it was still possible to update the `iframeUrl` via the `/in/:venueId/admin` endpoint.
- fixes https://github.com/sparkletown/internal-sparkle-issues/issues/580
- fixes https://github.com/sparkletown/internal-sparkle-issues/issues/206
> fix updateVenue function to properly update iframeUrl + simplify implementation

- functions/venue.js
Fix bug introduced in https://github.com/sparkletown/sparkle/pull/1274
```
Error: Error occurred while parsing your function triggers.
/home/circleci/project/functions/venue.js:63
export const ZOOM_URL_TEMPLATES = [
^^^^^^
SyntaxError: Unexpected token 'export'
at wrapSafe (internal/modules/cjs/loader.js:1063:16)
at Module._compile (internal/modules/cjs/loader.js:1111:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Module.require (internal/modules/cjs/loader.js:1036:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/circleci/project/functions/index.js:36:15)
at Module._compile …
```
> fix unsupported ES6 syntax in backend functions

- src/api/sounds.ts
- src/index.tsx
(technically this fix would be better made to `staging`, then deployed through our full chain to `master` and then `env/kotr`, as this will be an issue for everywhere that uses the new custom sounds feature, and technically probably just everywhere since it loads the sounds regardless of whether the venue uses them or not currently)
---
This is a follow on to https://github.com/sparkletown/internal-sparkle-issues/issues/388 / 
https://github.com/sparkletown/sparkle/pull/1269 to fix a minor bug.
---
Currently the app is trying to fetch the sounds straight away, but the firestore security rules prevent loading them unless you're logged in, resulting in errors such as:
- https://app.bugsnag.com/sparkle/sparkle-platform/errors/6040d30b803da5001819af2c?event_id=6052010d0073ab2e806c0000&i=sk&m=n …
> [ENV/KOTR] wait till auth is loaded before loading custom sounds

- src/store/reducers/Chat.ts
closes https://github.com/sparkletown/internal-sparkle-issues/issues/491
Change the default value of isChatSidebarVisible to false.
> ChatSideBar should be closed when you enter venue

- src/scss/global.scss
closes sparkletown/internal-sparkle-issues#503
closes sparkletown/internal-sparkle-issues#592
Before: 
After: 
Also, not sure how this is done but this needs to be deployed to Bigtop's environment asap
> Make scrollbars more visible

- src/pages/Admin/Details/ValidationSchema.ts
- src/pages/Admin/Venue/DetailsValidationSchema.ts
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/476 
(only partly fixes because the existing over 20 character room names in the database need to be changed/handled)
How it looks:
> Validate room name length

- src/components/molecules/UserProfilePicture/UserProfilePicture.styles.ts
- src/scss/constants.scss
We initially attempted a fix for this in https://github.com/sparkletown/sparkle/pull/1268, but it seems that in certain cases the layering issue still existed.
This PR fixes that by ensuring that all of the reactions are within the same 'stacking context', so that their layering applies as expected: 
- Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/551
- Supercedes https://github.com/sparkletown/sparkle/pull/1317
We also ensure that the back button sits above the user's avatar pictures:
- Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/607
---
> **Note:** In these screenshots below, I have hacked the code so that my user is 'sitting in every seat', to simplify showing many reactions/shoutouts/etc 'at once', and viewing how they overlap with one …
> fix reactions + back button layering issues

- package-lock.json
- package.json
- src/components/templates/Playa/Playa.tsx
- src/pages/VenueEntrancePage/VenueEntrancePage.tsx
closes https://github.com/sparkletown/internal-sparkle-issues/issues/160
---
We're currently using `"typescript": "^3.9.3"`:
- https://github.com/sparkletown/sparkle/blob/staging/package.json#L156
The latest version is `4.2.4`:
- https://github.com/microsoft/TypeScript/releases/tag/v4.2.4
There have been a number of releases since our current version, each adding new features, and their own 'breaking changes' categories:
- https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/ (this is the version we are currently on)
- ⚠️ ⚠️ ⚠️ **https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#breaking-changes (so these probably don't matter here)**
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/
- …
> Bump typescript from 3.9.3 to 4.2.4

- package-lock.json
- package.json
**Note:** This PR can only be merged once https://github.com/sparkletown/sparkle/pull/1320 is, as it requires features from the newer versions of TypeScript.
---
Adds `react-use`, which contains many React hooks for common needs/use cases, without having to reinvent the wheel each time:
- https://github.com/streamich/react-use
closes https://github.com/sparkletown/internal-sparkle-issues/issues/628
> add react-use dependency

- .github/workflows/firebase-hosting-pull-request.yml
We originally removed the `synchronize` event in https://github.com/sparkletown/sparkle/pull/1130 based on https://github.com/github/docs/issues/2257#issuecomment-772884922 + https://github.com/sparkletown/internal-sparkle-issues/issues/163#issuecomment-772206423
It seems that this had the unwanted side effect of not re-running when we push new code to a PR branch, which is sort of exactly when we want it to run.
Later in that thread (https://github.com/github/docs/issues/2257#issuecomment-799924192), someone shared a better resource, which clarifies further:
- https://github.community/t/what-is-a-pull-request-synchronize-event/14784/3
- > Thanks for the follow up. What this implies is that if you push a new commit to the HEAD ref of a pull request then this “synchronize” event will be …
> Ensure 'deploy preview environment' workflow runs when code is changed

- src/components/molecules/NavSearchBar/NavSearchBar.tsx
closes: https://github.com/sparkletown/internal-sparkle-issues/issues/678
There are 2 variables for search query: 
1. `searchInputValue` which is synchronized with the text that is written in the input field.
2. `searchQuery` which is changed with a delay (debounced `searchInputValue`) to reduce the number of search requests.
> Fix input value clearing on x-icon click

- src/components/atoms/InputField/InputField.tsx
based on discussions I decided to quickly move `ref` of the `InputField` component from `div` to `input` direclty
https://github.com/sparkletown/sparkle/pull/1343#discussion_r623564823
https://github.com/sparkletown/sparkle/pull/1299#discussion_r623554069
> Move InputField ref from div to input

- src/pages/VenuePage/VenuePage.tsx
- src/settings.ts
This greatly improves UX (User eXperience) by not only making page/tab
show the location, but also making browser history useful.  Without this
change you get the exciting "Sparkle" as the title (hardcoded in index.html)
for every page.
Joint work with @margulies where I was "git grep"ing and he was editing and trying it out.
Originally was sent (with vendoring) as #1386 against `env/ohbm`. This PR contains only the first commit from that PR (cherrypicked), without ohbm vendoring.
> add PLATFORM_BRAND_NAME + set page title in VenuePage based on current venue name

- src/components/organisms/EditProfileModal/EditProfileModal.tsx
- src/components/organisms/ProfileModal/EditProfileForm/EditProfileForm.tsx
- src/pages/Account/Profile.tsx
- src/settings.ts
Not sure if this is already taken care of (in which case, please close this PR), but this changes the max alloted char count for user names from 16 to ~30~ 40. If a different number would be preferred, just let me know and I'll make the change.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/670
> increase profile name max length to 40

- src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx
- src/components/organisms/EditProfileModal/EditProfileModal.tsx
- src/components/organisms/ProfileModal/EditProfileForm/EditProfileForm.tsx
- src/pages/Account/Profile.tsx
- src/settings.ts
Custom avatars are now fetched and used if they exist in the database. Otherwise the component fallbacks to the default ones.
This is a partial implementation of the whole feature. As already discussed with Sofi, the admin part of this is (optional) for now, but will be required in the near future.
Partially fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/673
> add support for custom default avatars

- src/settings.ts
This greatly improves UX (User eXperience) by not only making page/tab
show the location, but also making browser history useful.  Without this
change you get the exciting "Sparkle" as the title (hardcoded in index.html)
for every page.
Joint work with @margulies where I was "git grep"ing and he was editing and trying it out.
1st commit is generic and could be applied (cherrypicked) to the main code base.  2nd commit is OHBM vendoring. Let me know if there is another/better way to vendor it.
> [env/ohbm] set venuePage HTML document title basing off PLATFORM_BRAND_NAME

- .circleci/config.yml
The CirlceCI build was timing out when trying to delete functions that had been previously deployed, but since removed, as it was waiting for user confirmation to do so.
Looking at the help for `firebase deploy`, the solution is straightforward:
```
⇒  npx firebase deploy --help
Usage: firebase deploy [options]
..snip..
-f, --force              delete Cloud Functions missing from the current working directory without confirmation
```
---
> The CI build for this is failing when trying to deploy the functions. Looks like our current CI script doesn’t pass correct flags to say ‘yes it’s ok to delete functions that are no longer present in our config’, which causes it to hang waiting for user input until it times out.
> 
> - https://app.circleci.com/pipelines/github/sparkletown/sparkle/6062/wo …
> fix CircleCI config to allow firebase deploy to remove deleted functions

- src/components/templates/PartyMap/components/Map/MapRoom.scss
Fixes sparkletown/internal-sparkle-issues#721, when mousing over certain rooms, their aspect ratio changes. This only seems to happen with some images - but not others
> removed flex-shrink from the room img

- src/components/templates/Audience/Audience.tsx
- src/components/templates/PartyMap/components/Map/hooks/usePartygoersBySeat.ts
There is a separate check for FireLane (column) so should be ok in that regard
now that it would return True for 0, 0
Closes #1422
> fix logic in Auditorium (v1) where row/column 0 is treated as false instead of being a valid seat

- src/settings.ts
I have tried with 1200 and it still works ok.  The next UX fiasco which is not
fixed in this PR anyhow is "Show more posters" for a search query which has no
more to show.
> increase number of poster previews shown from 12 to 48

- src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
- src/types/venues.ts
Added an initial fix to enable setting the start date for the schedule using `start_utc_seconds` in `venue`. Planning to develop this further, but having this feature available for testing purposes would be helpful at this stage.
> add optional scheduleStartDate to DB + force NavBarSchedule to start from that date when present

- src/components/templates/PosterHall/PosterHall.tsx
- src/hooks/posters.ts
- src/utils/text.ts
**Note:** This is a re-created PR (to fix CI issues/etc) for the work tested & developed by @yarikoptic in #1443 
**Edit:** While the original PR accidentally overwrote the commit history, that has since been fixed and restored. Details in https://github.com/sparkletown/sparkle/pull/1460#issuecomment-850127899
---
This is basically a copy of #1443 + some additions/tweaks.
The reason for copying it was to test it & slightly clean up the code
closes #1391
closes #1453 
> At large closes #1391 (**Edit by @0xdevalias:** also closes https://github.com/sparkletown/internal-sparkle-issues/issues/745) although remains notably suboptimal.  With settings @margulies came up with seems to go a few steps further than my exploration (initial commit) 
> - additional explicit trimming of the search query …
> improve PosterHall search by adjusting fuse.js options + related

- scripts/deploy-master-to-prod-envs
- scripts/pr-show-commits
- scripts/pr-unresolved-review-comments
- `scripts/deploy-master-to-prod-envs`: Basic hacky bash script to deploy `master` to all(?) of our environments
- `scripts/pr-show-commits`: Uses the GitHub CLI to call the GitHub API to retrieve all of the commits for a given PR (useful for quickly making the list of included commits for the description in deployment PRs)
- `scripts/pr-unresolved-review-comments`: Uses the GitHub CLI to call the GitHub GraphQL API to list the unresolved review comments for the specified PR
> add my engineering QoL helper scripts

- src/components/molecules/NavBar/NavBar.tsx
- src/components/templates/PosterHall/PosterHall.tsx
- src/components/templates/PosterHall/components/PosterPreview/PosterPreview.tsx
- src/utils/url.ts
The changes in this PR basically pave the way to us being able to use React Router for relative link navigation, rather than having to entirely load the application every time someone changes spaces (or as @yarikoptic describes it: the "blue screen of sparkle")
- https://reactrouter.com/web/api/history
- > `push(path, [state])` - (`function`) Pushes a new entry onto the history stack
It adds this support in `openUrl`, `openRoomUrl`, and `enterVenue` within `utils/url`.
It uses this in only 2 places currently (we can add more in future followup PRs):
- the `backToParentVenue` button in the `NavBar` component
- within the `PosterPreview` component when accessing a `PosterPage`
I want to keep the scope of this PR fairly small for now, as while it does increase the perceived performance of …
> refactor openUrl/openRoomUrl/enterVenue to allow custom openers + use React Router for navigation in PosterPreview / NavBar's back button

- src/utils/text.ts
false positive statement: https://github.com/github/codeql/issues/5964#issuecomment-850344692
Verified by timing given in the https://github.com/github/codeql/issues/5964
example
$> cat ./test.js
/("[^"]*?"|[^"\s]+)+X/.test("!!!!!!!!!!!!!!!!!!!!!!!!!!!")
$> time nodejs ./test.js
nodejs ./test.js  8.92s user 0.01s system 99% cpu 8.931 total
against our lookahead (added a few more ! for a good measure to no effect):
$> cat ./test.js
/("[^"]*?"|[^"\s]+)+(?=\s*|\s*$)/.test("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
$> time nodejs ./test.js
nodejs ./test.js  0.10s user 0.01s system 100% cpu 0.113 total
and note that it is not per se about ! but any non "\s (a few less chars here
-- time is scarse):
$> cat ./test.js
/("[^"]*?"|[^"\s]+)+X/.test("########################")
$> time nodejs …
> Pay the @debt - it was a false positive

- src/components/templates/PosterHall/components/PosterPreview/PosterPreview.tsx
- src/components/templates/PosterPage/PosterPage.tsx
Poster number is important information since people refer to their posters by
numbers for easy finding/association/check if in the right place.  But it was
nowhere shown.
I guess ideally it should not be melded into the same `<element>` as title, but
this is the fastest and easiest way since title is in `<p>` and we do not want to
break it all across multiple lines etc.  Specific recommendations or better
tune up commits pushed directly would be most welcome to expedite this
PR.
Search for number yet to be supported (will see if could do in #1443) and is
orthogonal IMHO to having them displayed.
> show poster number alongside the title in PosterPreview / PosterPage

- src/components/organisms/EventModal/EventModal.scss
- src/components/organisms/EventModal/EventModal.tsx
This is how it would look like with this PR (edit: title is no longer rendered so must not be markdown)
in comparison to 
Closes #1505
> More markdown: event modal description

- src/components/templates/PartyMap/components/RoomModal/RoomModal.scss
discovered a small UI "bug" in the RoomModal while reviewing #1538
the scrollbar of the description area was always visible ( even if there is nothing to scroll )
\+ applied styling to it
BEFORE
* short description (scrollbar is not needed)
* long description (scrollbar is needed)
AFTER
* short description (scrollbar is not needed)
* long description (scrollbar is needed)
> Stylize scrollbar in RoomModals and show it only when needed

- src/components/templates/PartyMap/components/Map/MapRoom.tsx
Minor bug fix to return prior functionality to covert room type. The recent update to this code in https://github.com/sparkletown/sparkle/pull/1427 seems to have allowed unclickable and mapframe room types to scale on hover. This PR reverts that change.
> fix covert room type classes in MapRoom to not scale on hover

- src/components/organisms/AuthenticationModal/InitialForm/InitialForm.tsx
- src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
- src/pages/Account/Login.tsx
partially closes https://github.com/sparkletown/sparkle/pull/1523
Removes the standard registration method (while still allowing existing accounts to login) in preference of the SSO flow.
Initial View:
Login View:
Reset Password View:
> [env/ohbm] disable generic email/password registration method

- src/hooks/posters.ts
This is an attempt to weight titles more heavily in the search so that obvious matches appear towards the top of the list. 
fixes https://github.com/sparkletown/sparkle/issues/1604
---
Follow on from https://github.com/sparkletown/sparkle/pull/1578 which added more weight to `authorName` and `authors`
> increase post.title weight in search within PosterHall's usePosters hook

- src/settings.ts
Change user location update frequency from `5 mins` to `120 mins` for a (theoretically maybe) slight performance improvement.
> [env/ohbm] increase user location update frequency from 5min to 120min

- src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
- src/hooks/events.ts
- src/settings.ts
- src/store/reducers/Cache.ts
- src/store/reducers/index.ts
To load the venue calendar, sparkle currently must download all venues (which takes about 30-45 seconds for OHBM), followed by downloading all events from all venues (takes another 10-15 seconds). In total, user must sit and wait for about 40-60 seconds before they can see the schedule. Most user won't wait that long.
This PR replaces the call to firebase to download venues and venues/events, and instead, it loads from the cached json file stored in gs://cache/events.json (or wherever we set it to). By loading from the gs://, the calendar can be opened almost as soon as the main venue opens. 
The cache is uploaded from a server that queries all venues/events and we can run this as frequently as we need - during our conference. Any server with firebase admin sdk configured can do the …
> load venue events from pre-cached content stored in gs://

- src/hooks/posters.tsx
Originally the intent was to store first randomization of posters and reused it on re-renders of `PostersProvider` but instead the check
```javascript
if (isEmptyQuery && isPostersLoaded && previousPosterVenues.length === 0) {
setPreviousPosterVenues(shuffledPosterVenues);
}
```
wasn't properly done because of a typo.
> [env/ohbm] fix PostersProvider causing posters to re-randomize on render

- src/pages/Account/Account.scss
a follow-up PR of https://github.com/sparkletown/sparkle/pull/1654
`display: block` property of `Profile__summit-snap` was overwritten by `display: flex; ` of `.profile-picture-button`.
So I just changed the order of the rules as a quick fix.
> Fix the order of the styles

- functions/.runtimeconfig.json.example
- functions/auth.js
- functions/package-lock.json
- functions/package.json
- functions/src/utils/agora.js
- functions/src/utils/assert.js
- functions/src/utils/twilio.js
- functions/venue.js
- functions/video.js
- src/api/video.ts
- src/components/organisms/Room/Room.tsx
- src/components/templates/Jazzbar/components/JazzBarRoom/Room.tsx
- src/components/templates/Playa/Video/Room.tsx
- src/hooks/twilio.ts
partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/748
See references/overview in 🔒 https://github.com/sparkletown/internal-sparkle-issues/issues/748#issuecomment-868132831
This will be used as part of the `TalkShowStudio` (added in https://github.com/sparkletown/sparkle/pull/1469), specifically where it uses Agora for it's video features instead of Twilio.
- `npx firebase --project staging functions:config:set agora.app_id=REDACTED agora.app_certificate=REDACTED`
- Docs on how to do this: https://docs.agora.io/en/Interactive%20Broadcast/faq/token_cohost
- This will also require changes to the app logic (which is OOS of this PR): https://docs.agora.io/en/Interactive%20Broadcast/faq/token_cohost#2-change-the-app-logic
This PR is focussed on the backend …
> add secure dynamic token generation for agora video

- src/components/organisms/ChatSidebar/ChatSidebar.tsx
- src/hooks/chatSidebar.ts
Fix for venue chat as per https://github.com/sparkletown/internal-sparkle-issues/issues/824
* Fixed venue chat name change when going back from room to venue map
closes https://github.com/sparkletown/internal-sparkle-issues/issues/824
Patch described by @0xdevalias in https://github.com/sparkletown/internal-sparkle-issues/issues/824#issuecomment-863848152
> fix for venue chat name change when redirect back from room to venue map

- src/components/organisms/UserProfileModal/UserProfileModal.tsx
As per the call with @whilesocold @sofisparkle , we need to change the order of profile items
> move profile links to the bottom of the profile; move okta data to the top

- src/components/organisms/AuthenticationModal/InitialForm/InitialForm.tsx
- src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
- src/pages/Account/Login.scss
- src/pages/Account/Login.tsx
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/821
Looks like this now:
> Add bottom text to login form and replace 'Hubbers' with 'Okta users'

- src/components/organisms/AuthenticationModal/LoginForm/LoginForm.tsx
these changes were requested by @mobilevinay 
no github issue to link
looks like this now:
> [env/github] change login text

- src/settings.ts
partly fixes https://github.com/sparkletown/internal-sparkle-issues/issues/868
> [env/github] change default url to /v/register instead of sparkespaces.com

- src/settings.ts
Following up on https://github.com/sparkletown/sparkle/pull/1643
Closes https://github.com/sparkletown/internal-sparkle-issues/issues/662
Unsure why a backtick is used instead of quotation marks -- (for the variable thing you added, Glenn?) Just checking
> fix IFRAME_ALLOW by adding semicolons after both statements

- src/components/molecules/NavBar/NavBar.tsx
- src/components/templates/Jazzbar/JazzTab/JazzTab.tsx
- src/pages/VenuePage/TemplateWrapper.tsx
As per https://github.com/sparkletown/internal-sparkle-issues/issues/855
* Replaced `back to {href}` with `back` label for github only
> [env/github] Replace back to label with back

- src/components/molecules/Schedule/Schedule.tsx
- src/settings.ts
- src/utils/schedule.ts
closes https://github.com/sparkletown/internal-sparkle-issues/issues/884
* Added sorting for schedule room list
* Exception is 'Main Stage' room ( github related, always displays first in the list right after the 'my daily schedule' ( bookmarked events ) )
> Alexey petrov/sort schedule rooms alphabetically

- src/components/molecules/Schedule/Schedule.tsx
- src/settings.ts
- src/utils/schedule.ts
closes https://github.com/sparkletown/internal-sparkle-issues/issues/884
Added sorting for schedule room list
Exception is 'Main Stage' room ( github related, always displays first in the list right after the 'my daily schedule' ( bookmarked events ) )
> added github specific const + sort alphabetical order schedule rooms

- src/components/organisms/RenderMarkdown/RenderMarkdown.tsx
- src/components/organisms/RenderMarkdown/RenderMarkdownInner.tsx
Refactored `RenderMarkdown` to extract `RenderMarkdownInner` component + lazy load it with `React.lazy` / `Suspense`.
This has the effect of splitting all of the markdown rendering dependencies/plugins/etc (eg. `react-markdown`, `remark-gfm`, `remark-emoji`, `remark-external-links`, `rehype-sanitize`) into their own bundle chunk.
I pass through the raw `text` as the fallback for `Suspense`, so even before the markdown rendering chunk is loaded, the text can still be viewed in its raw form, allowing the site to still be usable even while the chunk is loading.
---
partially fixes sparkletown/internal-sparkle-issues#839
---
The overall bundle size only increases ever so slightly (from `3.49 MB` to `3.5 MB`), but we end up splitting off a new chunk of `202.07 KB`, reducing chunk 2 from `2.98 …
> refactor RenderMarkdown to extract RenderMarkdownInner component + lazy load it

- src/components/organisms/EventModal/EventModal.tsx
- src/utils/url.ts
Fixed event modal link url
* changed event room find logic
Since event room name could easily not be equal to the actual room title there were cases when we couldn't find a room with the event in question. Now whether user assigns `http://domain/{v || in}/roomName` or simply `roomName` as the event room we'll be able to determine the room to redirect him into
Fixes #1622
fixes #1585
> fix event room finding logic used to determine event room url

- src/components/molecules/NavSearchBar/NavSearchBar.tsx
Fixed `NavSearchBar` to filter out rooms that aren't enabled (and events in those rooms) from search results.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/147
**Note:** I haven't tested these changes in a clickthrough, so that should definitely be done before merging this PR.
> fix NavSearchBar to filter out rooms that aren't enabled (and events in those rooms) from search results

- src/pages/Admin/Venue/DetailsForm.tsx
`DetailsForm` seems to rely on some styles that are currently defined in `Admin.scss` (or another file with similar styles that were defined in 'global scope'). When we split our bundle in https://github.com/sparkletown/sparkle/pull/1737 (or a similar PR around that time), these styles seemed to be lost in the process.
This PR is a quick hacky fix to import the styles from `Admin.scss`, and adds some `@debt` notes to properly clean this up and separate the needed styles to the correct location in future.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/900
---
Note that there is also another PR (see below) that will fix this + also clean up associated tech debt, but given it's larger in scope, I figured getting a quick fix out sooner was better to unbreak the admin …
> quick fix for toggle/etc styles in DetailsForm in admin (v1)

- functions/src/utils/agora.js
- functions/video.js
fixes `TypeError: Cannot read property 'app_id' of undefined` that happens when deploying functions to an environment that doesn't have the agora config keys (introduced in #1673) in it's function config:
```
Error: Error occurred while parsing your function triggers.
TypeError: Cannot read property 'app_id' of undefined
at Object.<anonymous> (/home/circleci/project/functions/src/utils/agora.js:7:28)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Module.require (internal/modules/cjs/loader.js:1036:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> …
```
> fix TypeError: Cannot read property 'app_id' of undefined + add assertValidAgoraConfig

- src/components/organisms/WithNavigationBar/WithNavigationBar.scss
Some changes made in #1251 caused the `height: 100%` to be removed from `WithNavigationBar`, which lead to some spaces such as the `Embeddable` template breaking/displaying weirdly.
This PR is a 1 line change to fix that back up again.
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/747
> fix WithNavigationBar to restore height: 100%

- package-lock.json
- package.json
Bumps `redux` from `4.05` to `4.1.0`.
Changelog:
- https://github.com/reduxjs/redux/releases/tag/v4.1.0
- > This release shrinks our bundle size via error message extraction, updates several error messages for clarity, and optimizes our list of runtime dependencies.
- > Overall, version 4.1 shrinks from 2.6K min+gz to 1.6K min+gz thanks to these changes.
This is also a pre-requisite to upgrading to `@reduxjs/toolkit` `1.6.0`, which will come in a followup PR:
- https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.0
> Bump redux from 4.0.5 to 4.1.0

- package-lock.json
- package.json
Bumps `@reduxjs/toolkit` from `1.5.0` to `1.6.0`
Changelog:
- https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.0
- > This release adds the new RTK Query data fetching APIs to Redux Toolkit. It also adds multiple new options to `createAsyncThunk` for including meta fields and working with results, updates dependencies to Redux 4.1 and Immer 9, and includes a complete rewrite of our build toolchain with additional "modern" build artifacts in the package.
- https://redux-toolkit.js.org/rtk-query/overview
Note that this update has a dependency on `redux` `4.1.0`, as per:
- https://github.com/sparkletown/sparkle/pull/1794
We only use `@reduxjs/toolkit` in 1 file at the moment, and for a fairly minimal use case at that (we only use `createAsyncThunk`):
- …
> Bump @reduxjs/toolkit from 1.5.0 to 1.6.0

- functions/venue.js
- src/pages/Admin/Venue/DetailsForm.tsx
When editing a venue with `parentId` the function updates the sovereign venue with the values from the current one, because they were provided with spread operator. Now the sovereign venue data is being passed instead.
> fix admin v1 edit venue functionality

- src/components/organisms/AppRouter/Provided.tsx
In order not to have console errors in browsers when using `React.Fragment` like in the image,
a default no-operation `EmptyProvider` wraps `children` in `Provided`
> Use EmptyProvider instead of React.Fragment in Provided

- src/components/templates/PartyMap/components/Map/MapRoom.tsx
makes sure the correct styles match the correct elements. already fixed in staging but for some reason not in env/github
I don't think there is an issue to link- this was just discussed over slack/zoom.
> [env/github] make unclickable rooms look unclickable

- src/components/atoms/UserAvatar/UserAvatar.tsx
- src/components/molecules/Chatbox/Chatbox.tsx
- src/components/organisms/ChatSidebar/ChatSidebar.tsx
- src/components/organisms/ChatSidebar/components/VenueChat/VenueChat.tsx
- src/hooks/useRoles.ts
- src/hooks/useUser.ts
- src/hooks/useVenueChat.ts
- src/hooks/useVenueUserStatuses.ts
- src/pages/Admin/Admin_v2.tsx
Cleans up some tech debt, makes more effective use of memoing in `useSelector` in places, and uses `React.memo` to create 'pure' functional components.
This was all driven from using `whyDidYouRender` + the react performance profiler + `useDebugWarnLog` to track down and isolate the areas needing to be fixed up.
> refactor VenueChat and related for performance

- src/pages/VenuePage/TemplateWrapper.tsx
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/661
Previously while waiting for the redirect, `TemplateWrapper` would 'fall through' and show the 'no venue' error, even when it eventually got there. We now `return <LoadingPage />` after starting the redirect to prevent this.
> render LoadingPage while we wait for the redirect to complete in TemplateWrapper instead of showing invalid error

- src/pages/VenuePage/VenuePage.tsx
- src/utils/userLocation.ts
`updateCurrentLocationData` runs on an interval, which is fine when only a couple of users, but the cumulative effect of many 100's-1000's of users seems to grind the platform to a halt at times.
Let's hack this location update interval out for now.
> [env/github] hack out updateCurrentLocationData to reduce user location update spam

- src/components/molecules/ProfilePictureInput/ProfilePictureInput.tsx
Possible fix for corner cases of https://github.com/sparkletown/internal-sparkle-issues/issues/927
Initially a default avatar image was shown when there was a missing `githubHandle` and there wasn't one already set as `pictureUrl`  . This gave wrong impression the avatar image was already pre-selected/uploaded.
Now `<ProfilePictureInput>` sets the actual value of `githubImageSrc` (and by extension `pictureUrl` when missing ) to be the default `/avatars/default-octocat-3.png`
There is still one edge case remaining, an invalid `githubHandle` that may produce invalid avatar URL e.g. `https://github.com/invalid-github-handle.png?size=120`. But this should be visible to user and not misinform there is a pre-set avatar so they can take the appropriate action.
> [env/github] Set default profile photo on Okta login

- src/components/organisms/AdminVenues/AdminVenues.tsx
- src/components/organisms/AppRouter/AdminSubrouter.tsx
- src/pages/Admin/VenueList/VenueList.tsx
Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/879
Original URL `/admin-ng/venue/creation` would have been picked up by 
```
<Route path="/admin-ng/venue/:venueId?">
```
misinterpreting the `/creation` segment as a `venueId`.
Now URL is renamed to be picked up by
```
<Route path="/admin-ng/create/venue">
```
for parity with
```
<Route path="/admin-ng/edit/:venueId">
```
> Change venue creation URL to avoid clash with other route

- src/pages/Admin/Venue/Rooms/RoomsForm.tsx
The field used in the types and conditional rendering is called `isLabelHidden` but the toggle (useForm) in the admin was called `isLabeled`. You can see that in the previous PR for the feature: https://github.com/sparkletown/sparkle/pull/1632
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/914
P.S. People should test their stuff before merging. 🔥
> fix room toggle for hidden label

- src/components/molecules/ImageInput/ImageCollectionInput.tsx
Closes https://github.com/sparkletown/internal-sparkle-issues/issues/716
Done as per https://github.com/sparkletown/internal-sparkle-issues/issues/716#issuecomment-839728182
'Select background image' info text won't appear unless background library collection is not empty
> removed background image library text if collection is empty

- src/components/organisms/EventModal/EventModal.tsx
Closes https://github.com/sparkletown/internal-sparkle-issues/issues/946
* Fixed incorrect event redirect to non-working url
* If room has an external URL, then an event that points to that room will redirect directly to that URL
> fixed external link redirect

- src/pages/VenueLandingPage/VenueLandingPage.tsx
don't know why the logic to only show the 'join event' button if there are no events exists, but this pr gets rid of that so the join button is always there
> make sure landing page join event button always shows

- src/components/templates/ExternalRoom/ExternalRoom.scss
- src/components/templates/ExternalRoom/ExternalRoom.tsx
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/961
> make the external room text look 'sparklier'

- src/components/molecules/NavBar/NavBar.scss
- src/components/organisms/NavBarSchedule/NavBarSchedule.scss
also gets rid of dark background like in the designs
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/986
before:
after:
> (schedule v3) make schedule show up on left 

- src/components/atoms/ButtonNG/ButtonNG.scss
Avoids the warning by using quoted strings like
```scss
"white"
```
instead of unqoted values like
```scss
white
```
```powershell
WARNING: You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $modifier'.
â•·
98 â”‚     &--#{$modifier} {
â”‚          ^^^^^^^^^
â•µ
src\components\atoms\ButtonNG\ButtonNG.scss 98:10  root stylesheet
```
> Remove SCSS warning by quoting ButtonNG variants' names

- src/settings.ts
The parent id had `/` in it and this will cause problems for newly created venues because the parent id should be the id of the venue with a slash.
closes https://github.com/sparkletown/internal-sparkle-issues/issues/994
> BM - fix parentId for newly created venues

- src/pages/Admin/Admin.tsx
- src/pages/Admin/EventsComponent.tsx
This reverts some commits from https://github.com/sparkletown/sparkle/pull/1382
Just a minimum effort to bring the functionality back for BM. Discussion here: https://github.com/sparkletown/internal-sparkle-issues/issues/712#issuecomment-902315202
> Revert "remove add events from right panel"

- src/pages/Admin/Venue/DetailsForm.tsx
bring the parentId field back to admin v1 form with the default value == "playa" as per @sofisparkle's request.
Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1085
> Bring parentId field back to admin v1

- functions/venue.js
- src/pages/Admin/Admin.scss
- src/pages/Admin/Admin.tsx
- src/pages/Admin/AdminVenuePreview.tsx
- src/types/venues.ts
- src/utils/error.ts
- src/utils/venue.ts
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1057
This PR:
* extends BaseVenue type by adding `createdAt: number` and `updatedAt: number` fields (data is stored in UTC ms)
* saves the information of the timing when a venue was created and updated
* adds sorting options to admin v1 venue list by `A-Z`, `Z-A`, `newly created first`, `oldest first`
* shows venue creation and venue update time in admin v1
> Sort venues by creation date in Admin V1

- src/pages/Admin/MapPreview/MapPreview.tsx
Save button was working only once because of a false check inside the function and it's memoization.
This check already exists in the component and it's disabled prop.
`useAsyncFn` also handles this automatically.
> [env/burn-staging] fix bulk room save button

- src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
eventRoom logic was ran only for the event's venue Id and it wasn't checking for related venues and their rooms. Now the logic will run through all of the related venue rooms and check if that room exists.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1086
> [env/burn-staging] check for eventRoom in related venues

- src/components/atoms/UserAvatar/UserAvatar.tsx
- src/components/molecules/NavSearchBar/NavSearchResult.tsx
- src/components/molecules/UserProfilePicture/UserProfilePicture.tsx
- src/components/organisms/ChatSidebar/components/OnlineUser/OnlineUser.tsx
- src/components/organisms/ChatSidebar/components/PrivateChatPreview/PrivateChatPreview.tsx
- src/components/organisms/ChatSidebar/components/RecipientChat/RecipientChat.tsx
- src/components/templates/Audience/Audience.tsx
- src/hooks/useUploadProfilePictureHandler.ts
- src/settings.ts
- src/utils/image.ts
- storage.rules
We now use Imgix to resize user avatars in the chat panel.
This reduces network payload for avatars by ~4-5x, improves CPU performance and UX.
This is the first iteration to serve optimized images. We'll need to follow up by serving optimized images in the AnimateMap and other places.
This introduces two debts points:
1. A duplication of avatar image sizes between SCSS and the TSX files - ideally we should have one source of truth
2. Hardocded configuration value inside settings.ts - this should come from the env
If someone has a quick win for the above, great. If not, let me know and let's follow-up separately
> Serve resized user avatars in Chat panel 

- src/components/organisms/ChatSidebar/components/PrivateChats/PrivateChats.scss
Removes search icon shift
Before: 
After:
> Removes search icon shift

- src/components/molecules/ScheduleItemNG/ScheduleItemNG.tsx
- src/pages/EmergencyViewPage/EmergencyViewRoom.tsx
This significantly reduces time to load the page
https://burn.sparklever.se/m/playa 
(only images)
Before
After
> Serve resized venue images in the schedule and emergency view

- craco.config.js
Prevent error on `npm start`
```sh
> craco start
(node:68692) UnhandledPromiseRejectionWarning: TypeError: Cannot read p
roperty 'options' of undefined
```
> Craco blows up w/o the check

- src/components/templates/ArtPiece/ArtPiece.scss
- src/components/templates/ArtPiece/ArtPiece.tsx
- src/types/VideoAspectRatio.ts
Resolves 
- https://github.com/sparkletown/internal-sparkle-issues/issues/1132
Removed default anamorphic aspect ratio and added `max-width` and `max-height` of 100% to `ArtPiece__aspect-container`.
From comment https://github.com/sparkletown/internal-sparkle-issues/issues/1132#issuecomment-908940158:
>  -  going with @Sparkle-T insight and setting max width and max height to be 100% on the aspect ratio container;
>  - Height remains 100% to keep the layout with the video strip at the bottom in place;
>  - Removed the default aspect setting class i.e. no default aspect set;
>  - Now the value `anamorphic`, just like `16:9` previously, can be set through DB field `videoAspect` at the venue itself.
> [env/burn-staging] Fix art piece aspect ratio and going over 100% width/height

- src/components/molecules/Loading/Loading.tsx
- src/components/organisms/ChatSidebar/ChatSidebar.scss
Fix for regression in:
- https://github.com/sparkletown/sparkle/pull/2117
Comment (https://github.com/sparkletown/sparkle/commit/c6b6346682d4f81d4e9e95591c7b6791ee03da1c#r55837037):
> this change is not backward compatible and causes <Loading /> to not render anything where it was being used before this PR. e.g ScheduleNg, EmojiPicker.
BONUS regression fix: round off square buttons in chat
**Before**:
**After**:
**![sparkle-chat-squares-01](https://user-images.githubusercontent.com/79229621/132002625-d9b86d1c-c18b-4155-8541-17283c1b982d.png)**:
> Default displayWhile to true in <Loading> to unbreak older uses

- src/components/templates/ExternalRoom/ExternalRoom.scss
- src/components/templates/ExternalRoom/ExternalRoom.tsx
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1168
fixed text wrapping. see example below
> Fix BM External Link page 2.0 text wrapping

- src/components/templates/ExternalRoom/ExternalRoom.scss
- src/components/templates/PartyMap/components/RoomModal/RoomModal.scss
- src/components/templates/PartyMap/components/RoomModal/RoomModal.tsx
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1167
Now it looks better for specific spaces
> Fix BM Modal popup styles

- src/pages/Account/Venue/VenueMapEdition/Container.tsx
- src/pages/Account/Venue/VenueMapEdition/DraggableSubvenue.scss
- src/pages/Account/Venue/VenueMapEdition/DraggableSubvenue.tsx
- src/pages/Admin/MapPreview/MapPreview.tsx
Run tab's bulk room edit wasn't showing the room labels and it was hard to figure out which room is which especially if they have the same logo. This now fixes the issue and displays the room title underneath the avatar.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1032
> add room labels to run tab in admin v3

- src/pages/Account/Venue/VenueMapEdition/Container.tsx
The field is handled properly everywhere and it's being used only in 1 single place. This change will just make it optional.
> make title in subvenuemap optional

- src/pages/VenuePage/VenuePage.tsx
Removes useConnect for all venues.
It seems to be the leftovers from the introduction of `useRelatedVenues`
> Removes useConnect for all venues

- src/scss/global.scss
Follow up to
- https://github.com/sparkletown/sparkle/pull/2099
Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/969
> [staging] Backport default dotted frame for focused buttons

- src/hooks/useUser.ts
- src/pages/VenuePage/VenuePage.tsx
- src/store/api/worldUsers.ts
- src/types/User.ts
- src/utils/selectors.ts
- src/utils/user.ts
Follows up https://github.com/sparkletown/sparkle/pull/2274
- Fixes a situation when `enteredVenueIds` is initially empty and then is never populated.
- Adds `enteredVenueIds?: never` to type `User`
- Updates `useUser` hook to return user location and removed `useWorldUserLocation` from `VenuePage`
> Follow up to "Move enteredVenueIds into UserLocation"

- src/components/organisms/NewProfileModal/NewProfileModalBody/NewProfileModalBody.tsx
Fixes a bug when the user profile modal is left open after a user logs out.
> Close profile modal after logout

- craco.config.js
- package.json
Makes plugin not display style order warning thus halting CI build and deployment process. Example of warnings displayed:
```
chunk 1 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/components/atoms/PortalVisibility/PortalVisibility.scss
despite it was not able to fulfill desired ordering with these modules:
* css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/components/molecules …
```
> Make mini-css-extract-plugin plugin ignore style order

- src/components/molecules/VenueRoomItem/VenueRoomItem.tsx
Instead of using the old default room (now portal) image, now the newly created spaces have the selected template icon as default.
> change default space icon to the template selected

- src/components/organisms/AdminVenueView/components/MapPreview/MapPreview.tsx
- src/components/organisms/AdminVenueView/components/VenueRoomsEditor/VenueRoomsEditor.tsx
Portal name was not being passed to the edit object and that's why the name was not showing when editing a space position/size.
Before:
After:
> show portal name when editing a space

- package-lock.json
Makes this run message go away:
```
Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
> Update caniuse library

- src/settings/spacesSettings.ts
Partially resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1298
Based on comment (https://github.com/sparkletown/internal-sparkle-issues/issues/1298#issuecomment-955594955):
> Final thing: need to enable - but hidden - firebarrel, until we account for this in the unified table template (it will act as a one-table conversation space // no central content).
> Return firebarrel in the Add Portal but hidden

- src/components/organisms/WorldStartForm/WorldStartForm.tsx
Adds world slug validation to prevent multiple worlds being created with the same world slug.
Related issue: https://github.com/sparkletown/internal-sparkle-issues/issues/1318
> add world slug validation for world create and edit

- src/components/molecules/SpaceEditFormNG/SpaceEditFormNG.tsx
The problem is that `values.image_file` is not passed down. However TS is crying because that doesn't exist in the `values` object, it's actually mutated by either the image component or useForm. That's why we can't simply pass it and we use spread operator to pass the whole thing and allow the function to get what it needs. It is a very hacky solution and now I understand why it was written this way in the other form.
Fixes: N/A
> fix auditorium logo upload in admin v3

- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
Resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1390
In short, portal URL is hidden in all cases except the template is `external` or the URL starts with `http` based on `isExternalPortal()` logic.
**External**:
**Embedded**:
> Hide portal URL if portal isn't external

- src/pages/WorldsDashboard/WorldsDashboard.tsx
By removing the fixed footer all together.
Resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1410
> Remove the home button in WorldsDashboard

- src/components/templates/PartyMap/components/Map/MapRoom.scss
> Fix room logo

- src/components/templates/PartyMap/components/Map/MapRoom.scss
> Fix logo on map

- src/pages/Admin/AdvancedSettings/AdvancedSettings.tsx
Fixes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/792
Removed `Portal Appearence` component from `Advanced` settings ( world )
This component already exists in the space settings ( appearence accordion section for `auditoruim` type of spaces )
> remove portal appearence from space advanced

- src/hooks/useAnalytics.ts
Add `try{}catch(e){ console.error(); }` as the simplest measure of not letting mixpanel break the pages.
> Lowest effort mixpanel bug fix

- src/components/molecules/AdminCheckbox/AdminCheckbox.scss
- src/components/molecules/AdminCheckbox/AdminCheckbox.tsx
- src/components/organisms/WorldAdvancedForm/WorldAdvancedForm.tsx
Previously `AdminCheckbox` would not toggle its state if label wasn't present ( `label={<></>}` was a workaround ). Now...
ON / OFF displays, no label:
ON / OFF displays, with label above:
> Add flip-switch vaiant to AdminCheckbox and fix labeless click bug

- src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
`useWorldEdit` no longer exists and it was accidentally merged. This PR unblocks staging and uses `useWorldById`
> add useWorldById in RegisterForm component

- src/pages/Admin/Details/Form/DetailsForm.tsx
Closes a minor bug in:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1282
Fixed an error with `worldId` being undefined resulting in an empty parent list
> Space setting parent selector list exclude outside spaces

- src/components/atoms/ImageInput/ImageInput.scss
- src/components/atoms/PortalVisibility/PortalVisibility.scss
Throwback to Friday's (12.11.21) play in the product. Adding `wrap` to portal appearance container
> Fixed portal & image styles

- src/components/molecules/ReactionsBar/ReactionsBar.scss
- src/components/molecules/ReactionsBar/ReactionsBar.tsx
- src/components/templates/Auditorium/components/Section/Section.tsx
- src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1214
Added noop + disabled styles if the `isReactionsMuted` is set to `true` in the admin
> Disable reactions audio button according to flag

- src/components/molecules/NavBar/NavBar.tsx
Resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1460
This button should no longer show up.
> Make Schedule button not show up in Admin side of NavBar

- src/pages/VenuePage/VenuePage.tsx
A simple change to show `NotFound` instead of `Loading` on missing `spaceId`
> Update the Loading/NotFound conditions in VenuePage

- src/components/organisms/AdminVenueView/components/VenueRoomsEditor/VenueRoomsEditor.tsx
- An unnecessary `img` was being rendered on top of the div which had the correct styles.
- Rooms can be always selected and you don't have to click on `back` to select a new one.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1470
> fixes the stretched images in spaces preview

- functions/venue.js
- src/components/atoms/BackButton/BackButton.tsx
- src/components/atoms/BackButton/index.ts
- src/components/molecules/NavBar/NavBar.tsx
- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
- src/components/molecules/SpaceEditFormNG/SpaceEditFormNG.tsx
- src/components/templates/Auditorium/components/AllSectionPreviews/AllSectionPreviews.tsx
- src/components/templates/Auditorium/components/Section/Section.tsx
- src/components/templates/ConversationSpace/ConversationSpace.tsx
- src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
Resolves 
- https://github.com/sparkletown/internal-sparkle-issues/issues/1487
by refactor of `<BackButton>` so it
- doesn't show up in admin context
- uses the proper slug to go back
- compiles 3 different modes of going back from parent components via its new `variant` prop
Bonus:
- fix for space slug -> space id read from portal URLs in order to test Auditorium back button
> fix BackButton visibility and linkability issues (take 2)

- src/components/templates/PartyMap/components/RoomModal/RoomModal.scss
**AV1 only**
Resolves #1505
No horizontal scrollbar anymore:
> Stop showing the horizontal scrollbar on the room modal

- src/components/molecules/NavBar/NavBar.tsx
- src/components/organisms/WorldAdvancedForm/WorldAdvancedForm.tsx
- src/components/templates/PartyMap/components/PortalModal/PortalModal.tsx
- src/components/templates/PartyMap/components/index.ts
- src/utils/schedule.ts
Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1475
by making a single check `shouldScheduleBeShown()` everywhere that factors in `DEFAULT_SHOW_SCHEDULE` if the world or the value for `showSchedule` is missing.
> Use shouldScheduleBeShown() everywhere to have same check

- src/components/organisms/AuthenticationModal/RegisterForm/RegisterForm.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1286
Fixed an issue with hardcoded redirect to `bootstrap` venue since `spaceSlug` was missing from the url params for new registration url
Fixed by replacing here:
`venueId` replaced by `spaceSlug` in the url params: 
Code of conduct questions:
`venueId` replaced by `spaceSlug` in the url params:
> replaced venue id with spaceslug param

- src/components/molecules/AdminSpaceCard/AdminSpaceCard.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1468
Fixed admin space card 'Edit' link url
Set `coverImageUrl` as a background url option
Fixes issues found during QA: https://github.com/sparkletown/internal-sparkle-issues/issues/1468#issuecomment-982558516
> fixed admin space card edit link + cover image url as background

- src/components/molecules/PortalAddModal/PortalAddModal.tsx
In some cases the ID of the venue is not the same as the slug and this prevents a portal from being successfully created.
> Fix for using slug instead of ID when upserting a portal

- src/components/molecules/NavBar/NavBar.tsx
Removes the home button from the admin navbar. It's not in any of the designs and the redirect location was wrong.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1516
> remove home button from navbar

- src/utils/embeddableUrl.ts
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1472
> Do not replace 'parent' param value with 'localhost' in twitch URLs

- .github/workflows/firebase-hosting-pull-request.yml
Github updated all node builds to node 16. This is causing some package issues. Pinning back to 14 until we can investigate more completely.
As a side note, we're using a really old version of firebase tools. 8.6.0. Latest is 9.23.0
> Pin firebase preview build to node 14

- src/components/organisms/AdminVenueView/AdminVenueView.tsx
- src/components/organisms/AdminVenueView/components/AdminPanel/AdminPanel.scss
- src/components/organisms/AdminVenueView/components/AdminPanel/AdminPanel.tsx
- src/components/organisms/AdminVenueView/components/AdminShowcase/AdminShowcase.scss
- src/components/organisms/AdminVenueView/components/AdminShowcase/AdminShowcase.tsx
- src/components/organisms/AdminVenueView/components/RunTabView/RunTabView.tsx
- src/components/organisms/AdminVenueView/components/SpaceTimingPanel/SpaceTimingPanel.tsx
- src/components/organisms/AdminVenueView/components/Spaces/Spaces.tsx
- src/components/organisms/WithNavigationBar/WithNavigationBar.scss
- src/components/organisms/WithNavigationBar/WithNavigationBar.tsx
- src/pages/Admin/Details/SpaceEditorStartPanel.tsx
- src/pages/SpacesDashboard/SpacesDashboard.scss
- src/pages/SpacesDashboard/SpacesDashboard.tsx
- src/pages/WorldEditor/WorldEditorAdvancedPanel.tsx
- src/pages/WorldEditor/WorldEditorEntrancePanel.tsx
- src/pages/WorldEditor/WorldEditorStartPanel.tsx
- src/pages/WorldsDashboard/WorldsDashboard.tsx
Some views in Admin have scrollbar issues.
1 Cutting off to certain elements when scrolled all the way down (now no more of that):
2. Double scrollbars (now only a single one displayed):
> Fix Admin scrollbar issues

- src/components/molecules/NavBar/NavBar.tsx
- src/settings/disableSettings.ts
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1142
Disables `photobooth` feature at staging using `DISABLED_DUE_TO_1142` constant
Created as a follow up for https://github.com/sparkletown/sparkle/pull/2392
> disable photobooth feature

- src/components/molecules/AdminSpaceCard/AdminSpaceCard.scss
- src/components/molecules/AdminSpaceCard/AdminSpaceCard.tsx
- src/scss/constants.scss
Not actually the border, but a tweak to the `box-shadow` color to be `--content--over-20a` so it contrasts the background which has `--content--under`.
Also, a fix for the time before `worldSlug` is loaded, the edit links are just `#`.
**Before**:
**After**:
> Make AdminSpaceCard border visible compared to the background

- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
- src/forms/nonIframeSpaceSchema.ts
Follow up for https://github.com/sparkletown/sparkle/pull/2631
Reference: https://doesitsparkle.slack.com/archives/C02DPU9KF1A/p1638364391412200
Spaces with no 'iframeUrl' couldn't be update due to an incorrect schema fields being used
> fixed noniframe space update schema

- src/components/atoms/SpacesDropdown/SpacesDropdown.tsx
- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
- src/components/molecules/SpaceEditFormNG/SpaceEditFormNG.tsx
- src/components/organisms/TimingEventModal/TimingEventModal.tsx
- src/pages/Admin/Details/Form/DetailsForm.tsx
Follow up rework of parent list options: sparkletown/internal-sparkle-issues#1461
Specifically fixes this issue: sparkletown/internal-sparkle-issues#1461 (comment)
Replaced name with slug to be used in the option list, as it proved to be more sustainable source of identification.
> Switch SpacesDropdown to using ID

- src/api/events.ts
- src/components/organisms/AdminVenueView/components/EventsView/EventsView.tsx
- src/components/organisms/NavBarSchedule/NavBarSchedule.tsx
- src/components/organisms/TimingDeleteModal/TimingDeleteModal.tsx
- src/hooks/events.ts
- src/hooks/useVenueScheduleEvents.ts
Trigger a refetch of events when they are likely to have changed.
This change applies to both attendee and admin side.
The debt in this PR needs to be picked up later.
Resolves https://github.com/sparkletown/internal-sparkle-issues/issues/1551
> Refetch events when they are likely to have changed

- src/components/atoms/SpacesDropdown/SpacesDropdown.scss
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1575
Add `max-height` and `overflow-y: auto` to have a scrollable dropdown
> add scroll to space dropdown list

- src/components/molecules/StartTable/StartTable.tsx
- src/components/molecules/TableComponent/TableComponent.tsx
- src/components/molecules/TablesUserList/TablesUserList.tsx
- src/components/templates/ConversationSpace/ConversationSpace.tsx
- src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
- src/components/templates/Jazzbar/JazzBarPage.tsx
- src/components/templates/Jazzbar/JazzBarSkeletonPage/JazzBarSkeletonPage.tsx
- src/components/templates/Jazzbar/components/JazzBarTableComponent/JazzBarTableComponent.tsx
- src/types/Table.ts
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1149
Removing default text placeholder + got rid of the `currentVenueSelector` usages in certain files ( returned undefined ) and replaced with a passed `venue` prop
> remove default jazzbar info

- src/components/molecules/NavBar/NavBar.scss
- src/components/molecules/NavBar/NavBar.tsx
- src/components/organisms/AdminVenueView/AdminVenueView.tsx
- src/pages/SpacesDashboard/SpacesDashboard.tsx
- src/pages/WorldEditor/WorldEditor.tsx
- src/pages/WorldsDashboard/WorldsDashboard.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1560
Admin dashboard will always show `Sparkle Admin` as the title + world that's currently being edited ( if any )
> replace space name with world name in admin nav bar

- src/components/atoms/ImageInput/ImageInput.scss
- src/components/organisms/PortalStripForm/PortalStripForm.tsx
- src/settings/spacePortalsSettings.ts
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1576
Before:
After:
> fix broken external portal icon

- src/components/organisms/PortalAddEditForm/PortalAddEditForm.scss
- src/components/organisms/PortalAddEditForm/PortalAddEditForm.tsx
- src/components/organisms/PortalStripForm/PortalStripForm.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1600
Error handling is present and existed before the changes:
Fixed: 
- Portal image display
- Edit button `onclick` handler (triggered by click on a div instead of text span)
> portal form UI fixes

- src/components/molecules/StartTable/StartTable.scss
- src/scss/constants.scss
a bit hacky solution that fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1606
not sure why only `StartTable` component needs `z-index`, and existing tables don't.. 😕
> Fix StartTable layer

- src/api/admin.ts
- src/components/atoms/ImageInput/ImageInput.tsx
- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
- src/components/organisms/PortalAddEditForm/PortalAddEditForm.tsx
- src/components/organisms/PortalStripForm/PortalStripForm.tsx
- src/forms/spaceEditSchema.ts
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1609
* Added default space logo icon uploaded per creation. 
* Made logo image optional ( since it's uploaded automatically there's no way it's gonna be missing )
* Made default portal icon to be parent space's icon
Before:
After:
> Fix default space logo icon

- src/components/organisms/NewProfileModal/EditingProfileModalContent/EditingProfileModalContent.tsx
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1608
when we remove the last profile link using `remove` function of `useFieldArray`, instead of setting `[]` to the `data`, it disappears, so this hacky solution is just to set an empty list of `profileLinks` if there are no profile links.
related issue: https://github.com/react-hook-form/react-hook-form/issues/871
> Fix deleting profile links

- src/components/templates/Jazzbar/JazzBar/JazzBar.tsx
This breaks jukebox functionality, but, that isn't used anywhere right now whereas iframe switching **is**
> Fix music venue iframe swithing

- src/components/molecules/AdminSpaceCard/AdminSpaceCard.tsx
- src/components/molecules/NavBar/components/NavBarLogin/NavBarLogin.tsx
- src/components/molecules/SecretPasswordForm/SecretPasswordForm.tsx
- src/components/organisms/AppRouter/AppRouter.tsx
- src/hooks/useAdminContextCheck.tsx
- src/pages/VenueEntrancePage/VenueEntrancePage.tsx
- src/pages/VenueLandingPage/VenueLandingPageContent.tsx
- src/pages/VenuePage/VenuePage.tsx
- src/pages/entrance/WelcomeVideo/WelcomeVideo.tsx
- src/settings/urlSettings.ts
- src/utils/url.ts
Couldn't reproduce what is described in
- https://github.com/sparkletown/internal-sparkle-issues/issues/1613
Instead tightened up the routing connected to entrance steps:
- URLs more in line with general strategy `/e/w/mysharkyworld/s/myconversationspace/1`
- use of `generateUrl` for more explicit and robust route generation
- removed ` spaceSlug &&` check since it is legacy and not needed
- added not-a-number check for the entrance step
- a bit more consolidation work in the URL constants
> Tighten up entrance steps routing

- src/components/molecules/SpaceEditForm/SpaceEditForm.scss
- src/components/molecules/SpaceEditForm/SpaceEditForm.tsx
- src/components/organisms/AdminVenueView/components/EventsView/EventsView.scss
- src/components/organisms/AdminVenueView/components/RunTabView/RunTabView.scss
- src/components/organisms/AdminVenueView/components/RunTabView/RunTabView.tsx
- src/components/organisms/AdminVenueView/components/SpaceTimingPanel/SpaceTimingPanel.scss
- src/components/organisms/AdminVenueView/components/SpaceTimingPanel/SpaceTimingPanel.tsx
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1584
* Add missing title + fixed styles in corresponding places its used 
* Fixed no-events message display
Before:
After:
After:
> add missing space settings title

- functions/index.js
Fix for failed builds due to missing `stats` dependency in firebase functions
> removed stats dependency from firebase functions

- src/api/admin.ts
- src/components/atoms/SpacesDropdown/SpacesDropdown.tsx
When editing a portal (without changing the image), the `image_url` would be set to undefined in the payload for the upsertRoom cloud function. This resulted in the cloud function wiping that field in the database and no images appearing in the attendee side. 
Simplifies the logic that deals with image uploads and doesn't wipe that field if a new image is not provided.
> Fix for wiping images when editing portals

- src/components/atoms/Dropdown/Dropdown.scss
- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/atoms/SortDropDown/SortDropDown.scss
- src/components/atoms/SortDropDown/SortDropDown.tsx
- src/components/atoms/SpacesDropdown/SpacesDropdown.scss
- src/components/atoms/SpacesDropdown/SpacesDropdown.tsx
- src/components/atoms/UserStatusDropdown/UserStatusDropdown.scss
- src/components/atoms/UserStatusDropdown/UserStatusDropdown.tsx
- src/components/molecules/Chatbox/components/ChatboxOptionsControls/ChatboxOptionsControls.tsx
- src/settings/placeholderSettings.ts
A first update to of `Dropdown` component that removes inline `stlyle`s from the `Select` component and fixes the prefix to not contain double dunder, thus not breaking BEM naming convention.
> Remove inline styles from <Select> in <Dropdown>

- src/components/molecules/TableComponent/TableComponent.tsx
min-height is already set by the CSS on TableComponent and specifying the
height directly can lead to clipping issues when the component will
resize nicely anyway
> Remove height specification on tables outside jazz bar

- src/hooks/events.ts
- src/pages/VenueLandingPage/VenueLandingPageContent.tsx
This had not been updated after the world event
refactor.
Resolves https://github.com/sparkletown/internal-sparkle-issues/issues/1691
> Show world events on entrance pages

- src/pages/VenuePage/VenuePage.tsx
Resolves
- https://github.com/sparkletown/internal-sparkle-issues/issues/1726
Fixed reading `userId` from correct place so the visited space and world would get saved thus not dropping the new users out of the space and into the entrance steps.
> Enable new users to proceed to their space

- src/components/admin/Header/Header.tsx
The CI was broken because of forgotten `npm run reformat`
> fix broken ci

- src/utils/error.ts
- src/utils/validation.ts
I don't know the correct test that should be performed ATM, but this addition will at least not put the blame at Firebase due to hard to understand error.
> Add informative error in `testWorldBySlugExists()` validation

- src/components/molecules/WorldCard/WorldCard.tsx
Removes the `nowrap` style to fix the long world names and descriptions that extend outside of the screen and force the browser to show horizontal scrollbar and hide the `Go to world` button.
**Old:**
**New:**
> remove whitespace-nowrap from WorldCard to display long text properly

- src/components/attendee/TableComponent/TableComponent.module.scss
Adds flex-wrap to fix the table avatars in the TableComponent for both jazzbar and conversation space.
Fixes: https://github.com/sparkletown/internal-sparkle-issues/issues/1741
> fix table avatars appearing outside of the container

- src/components/molecules/TablesUserList/TablesUserList.tsx
- src/utils/string.ts
- src/utils/table.ts
Closes:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1687
Spaces with tables with have default table names `table1` to `table10`
Manually created tables will be named `New Table`
> replace new name for manually created tables

- src/components/attendee/IntersectingButton/IntersectingButton.tsx
- src/components/attendee/ScheduleOverlay/ScheduleOverlay.tsx
Fixes schedule event filtering. Previously it failed to match the events in the correct spaces due to an incorrect filter value comparison, resulting in errors such as empty schedule list or
> fix schedule space id filter

- src/components/admin/PortalStripForm.tsx
- src/components/admin/Toggle/Toggle.tailwind.ts
- src/components/admin/Toggle/Toggle.tsx
Resolves:
- https://github.com/sparkletown/internal-sparkle-issues/issues/1759
The previous version of the `<Toggle >` component used `register` to handle data. The new version switched the handling to `onChange()` handler on the `<input>` element which doesn't always capture the clicks (without `register` even more so).
This update moves the handler to `onClick()` for the `<label>` component and adds a bit of cleanup and comments to explain the logic behind it.
> Fix <Toggle> double click in <PortalStripForm>

- src/components/templates/Auditorium/components/SeatingBlock/SeatingBlock.tsx
- src/utils/error.ts
- src/utils/query.ts
Adding an assert error as a type of sparkle error and utilities to capture its info, like the place of it.
This is probably not an isolated issue since types can assume data is there and in certain form, but reading from DB might not produce it as expected. This assertion in `SeatingBlock` component will note it (at least in console for now) and not make the page break.
> Report error in rare cases secionId is missing

- functions/analytics.js
The node version on staging doesn't have .flat() in its prototype.
That's why it worked locally, but didn't work in staging
closes https://github.com/sparkletown/internal-sparkle-issues/issues/1641
> Replaces prototypal flat with lodash flatten
